run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - govet

linters-settings:
  govet:
    enable:
      - nilness
    disable:
      - shadow

issues:
  exclude-dirs:
    - docs
    - archeive
  exclude-rules:
    # Exclude linters from running on test files
    - path: _test\.go
      linters:
        - errcheck
        - govet
    # Exclude generated protobuf files
    - path: \.pb\.go
      linters:
        - all
  # Don't fail on existing issues - report only new
  max-issues-per-linter: 0
  max-same-issues: 0
