// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/proto/space-transfer.proto

package transferpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpaceTransfer_Export_FullMethodName     = "/mdemg.transfer.v1.SpaceTransfer/Export"
	SpaceTransfer_Import_FullMethodName     = "/mdemg.transfer.v1.SpaceTransfer/Import"
	SpaceTransfer_ListSpaces_FullMethodName = "/mdemg.transfer.v1.SpaceTransfer/ListSpaces"
	SpaceTransfer_SpaceInfo_FullMethodName  = "/mdemg.transfer.v1.SpaceTransfer/SpaceInfo"
)

// SpaceTransferClient is the client API for SpaceTransfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpaceTransferClient interface {
	// Export streams all data for a space_id from source to caller.
	// Chunks are sent in order: metadata → nodes → edges → observations → symbols → summary.
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SpaceChunk], error)
	// Import receives streamed chunks and writes them to the target Neo4j.
	// Returns a summary of what was created/skipped/failed.
	Import(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SpaceChunk, ImportResponse], error)
	// ListSpaces returns available spaces with node/edge counts and metadata.
	ListSpaces(ctx context.Context, in *ListSpacesRequest, opts ...grpc.CallOption) (*ListSpacesResponse, error)
	// SpaceInfo returns detailed metadata for a single space (for pre-import validation).
	SpaceInfo(ctx context.Context, in *SpaceInfoRequest, opts ...grpc.CallOption) (*SpaceInfoResponse, error)
}

type spaceTransferClient struct {
	cc grpc.ClientConnInterface
}

func NewSpaceTransferClient(cc grpc.ClientConnInterface) SpaceTransferClient {
	return &spaceTransferClient{cc}
}

func (c *spaceTransferClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SpaceChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SpaceTransfer_ServiceDesc.Streams[0], SpaceTransfer_Export_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportRequest, SpaceChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpaceTransfer_ExportClient = grpc.ServerStreamingClient[SpaceChunk]

func (c *spaceTransferClient) Import(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SpaceChunk, ImportResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SpaceTransfer_ServiceDesc.Streams[1], SpaceTransfer_Import_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SpaceChunk, ImportResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpaceTransfer_ImportClient = grpc.ClientStreamingClient[SpaceChunk, ImportResponse]

func (c *spaceTransferClient) ListSpaces(ctx context.Context, in *ListSpacesRequest, opts ...grpc.CallOption) (*ListSpacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSpacesResponse)
	err := c.cc.Invoke(ctx, SpaceTransfer_ListSpaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceTransferClient) SpaceInfo(ctx context.Context, in *SpaceInfoRequest, opts ...grpc.CallOption) (*SpaceInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpaceInfoResponse)
	err := c.cc.Invoke(ctx, SpaceTransfer_SpaceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpaceTransferServer is the server API for SpaceTransfer service.
// All implementations must embed UnimplementedSpaceTransferServer
// for forward compatibility.
type SpaceTransferServer interface {
	// Export streams all data for a space_id from source to caller.
	// Chunks are sent in order: metadata → nodes → edges → observations → symbols → summary.
	Export(*ExportRequest, grpc.ServerStreamingServer[SpaceChunk]) error
	// Import receives streamed chunks and writes them to the target Neo4j.
	// Returns a summary of what was created/skipped/failed.
	Import(grpc.ClientStreamingServer[SpaceChunk, ImportResponse]) error
	// ListSpaces returns available spaces with node/edge counts and metadata.
	ListSpaces(context.Context, *ListSpacesRequest) (*ListSpacesResponse, error)
	// SpaceInfo returns detailed metadata for a single space (for pre-import validation).
	SpaceInfo(context.Context, *SpaceInfoRequest) (*SpaceInfoResponse, error)
	mustEmbedUnimplementedSpaceTransferServer()
}

// UnimplementedSpaceTransferServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpaceTransferServer struct{}

func (UnimplementedSpaceTransferServer) Export(*ExportRequest, grpc.ServerStreamingServer[SpaceChunk]) error {
	return status.Error(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedSpaceTransferServer) Import(grpc.ClientStreamingServer[SpaceChunk, ImportResponse]) error {
	return status.Error(codes.Unimplemented, "method Import not implemented")
}
func (UnimplementedSpaceTransferServer) ListSpaces(context.Context, *ListSpacesRequest) (*ListSpacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSpaces not implemented")
}
func (UnimplementedSpaceTransferServer) SpaceInfo(context.Context, *SpaceInfoRequest) (*SpaceInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SpaceInfo not implemented")
}
func (UnimplementedSpaceTransferServer) mustEmbedUnimplementedSpaceTransferServer() {}
func (UnimplementedSpaceTransferServer) testEmbeddedByValue()                       {}

// UnsafeSpaceTransferServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpaceTransferServer will
// result in compilation errors.
type UnsafeSpaceTransferServer interface {
	mustEmbedUnimplementedSpaceTransferServer()
}

func RegisterSpaceTransferServer(s grpc.ServiceRegistrar, srv SpaceTransferServer) {
	// If the following call panics, it indicates UnimplementedSpaceTransferServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpaceTransfer_ServiceDesc, srv)
}

func _SpaceTransfer_Export_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SpaceTransferServer).Export(m, &grpc.GenericServerStream[ExportRequest, SpaceChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpaceTransfer_ExportServer = grpc.ServerStreamingServer[SpaceChunk]

func _SpaceTransfer_Import_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SpaceTransferServer).Import(&grpc.GenericServerStream[SpaceChunk, ImportResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpaceTransfer_ImportServer = grpc.ClientStreamingServer[SpaceChunk, ImportResponse]

func _SpaceTransfer_ListSpaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSpacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceTransferServer).ListSpaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpaceTransfer_ListSpaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceTransferServer).ListSpaces(ctx, req.(*ListSpacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceTransfer_SpaceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpaceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceTransferServer).SpaceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpaceTransfer_SpaceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceTransferServer).SpaceInfo(ctx, req.(*SpaceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpaceTransfer_ServiceDesc is the grpc.ServiceDesc for SpaceTransfer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpaceTransfer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mdemg.transfer.v1.SpaceTransfer",
	HandlerType: (*SpaceTransferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSpaces",
			Handler:    _SpaceTransfer_ListSpaces_Handler,
		},
		{
			MethodName: "SpaceInfo",
			Handler:    _SpaceTransfer_SpaceInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Export",
			Handler:       _SpaceTransfer_Export_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Import",
			Handler:       _SpaceTransfer_Import_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/space-transfer.proto",
}
