// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: mdemg-module.proto

package modulepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ModuleType defines the category of module
type ModuleType int32

const (
	ModuleType_MODULE_TYPE_UNSPECIFIED ModuleType = 0
	ModuleType_MODULE_TYPE_INGESTION   ModuleType = 1 // Perception - parses content into observations
	ModuleType_MODULE_TYPE_REASONING   ModuleType = 2 // Cognition - processes/re-ranks retrieval results
	ModuleType_MODULE_TYPE_APE         ModuleType = 3 // Active Participant - background maintenance tasks
	ModuleType_MODULE_TYPE_CRUD        ModuleType = 4 // CRUD - create/read/update/delete external entities
)

// Enum value maps for ModuleType.
var (
	ModuleType_name = map[int32]string{
		0: "MODULE_TYPE_UNSPECIFIED",
		1: "MODULE_TYPE_INGESTION",
		2: "MODULE_TYPE_REASONING",
		3: "MODULE_TYPE_APE",
		4: "MODULE_TYPE_CRUD",
	}
	ModuleType_value = map[string]int32{
		"MODULE_TYPE_UNSPECIFIED": 0,
		"MODULE_TYPE_INGESTION":   1,
		"MODULE_TYPE_REASONING":   2,
		"MODULE_TYPE_APE":         3,
		"MODULE_TYPE_CRUD":        4,
	}
)

func (x ModuleType) Enum() *ModuleType {
	p := new(ModuleType)
	*p = x
	return p
}

func (x ModuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_mdemg_module_proto_enumTypes[0].Descriptor()
}

func (ModuleType) Type() protoreflect.EnumType {
	return &file_mdemg_module_proto_enumTypes[0]
}

func (x ModuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleType.Descriptor instead.
func (ModuleType) EnumDescriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{0}
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MdemgVersion  string                 `protobuf:"bytes,1,opt,name=mdemg_version,json=mdemgVersion,proto3" json:"mdemg_version,omitempty"`                                           // MDEMG server version (e.g., "1.0.0")
	SocketPath    string                 `protobuf:"bytes,2,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`                                                 // Unix socket path for this module
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Module-specific configuration from manifest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_mdemg_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetMdemgVersion() string {
	if x != nil {
		return x.MdemgVersion
	}
	return ""
}

func (x *HandshakeRequest) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

func (x *HandshakeRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`                                        // Module identifier (from manifest)
	ModuleVersion string                 `protobuf:"bytes,2,opt,name=module_version,json=moduleVersion,proto3" json:"module_version,omitempty"`                         // Module version
	ModuleType    ModuleType             `protobuf:"varint,3,opt,name=module_type,json=moduleType,proto3,enum=mdemg.module.v1.ModuleType" json:"module_type,omitempty"` // Type of module (INGESTION, REASONING, APE)
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                                                // List of capabilities (e.g., ["parse:typescript", "parse:go"])
	Ready         bool                   `protobuf:"varint,5,opt,name=ready,proto3" json:"ready,omitempty"`                                                             // Whether module is ready to accept requests
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                                                              // Error message if not ready
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_mdemg_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *HandshakeResponse) GetModuleVersion() string {
	if x != nil {
		return x.ModuleVersion
	}
	return ""
}

func (x *HandshakeResponse) GetModuleType() ModuleType {
	if x != nil {
		return x.ModuleType
	}
	return ModuleType_MODULE_TYPE_UNSPECIFIED
}

func (x *HandshakeResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HandshakeResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HandshakeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_mdemg_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`                                                                          // Overall health status
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                                                             // Human-readable status message
	Metrics       map[string]string      `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Module-specific metrics (e.g., "requests_processed": "1234")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_mdemg_module_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeoutMs     int32                  `protobuf:"varint,1,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // Maximum time to wait for graceful shutdown
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                         // Reason for shutdown (e.g., "server_stop", "module_disabled")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_mdemg_module_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{4}
}

func (x *ShutdownRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ShutdownRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Whether shutdown completed successfully
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // Additional shutdown message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_mdemg_module_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{5}
}

func (x *ShutdownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShutdownResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceUri     string                 `protobuf:"bytes,1,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`                                                        // URI of source (e.g., "linear://workspace/issue/123", "file:///path/to.ts")
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`                                                  // MIME type or custom type (e.g., "text/typescript", "linear/issue")
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	mi := &file_mdemg_module_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{6}
}

func (x *MatchRequest) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *MatchRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MatchRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       bool                   `protobuf:"varint,1,opt,name=matches,proto3" json:"matches,omitempty"`        // Whether this module can handle the source
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0-1.0 confidence in handling (for priority when multiple match)
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`           // Why it matches/doesn't match
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	mi := &file_mdemg_module_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{7}
}

func (x *MatchResponse) GetMatches() bool {
	if x != nil {
		return x.Matches
	}
	return false
}

func (x *MatchResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *MatchResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceUri     string                 `protobuf:"bytes,1,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`                                                        // URI of source
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`                                                  // Content type
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                                                             // Raw content to parse
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional context (e.g., file path, timestamps)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_mdemg_module_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{8}
}

func (x *ParseRequest) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *ParseRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ParseRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ParseRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observations  []*Observation         `protobuf:"bytes,1,rep,name=observations,proto3" json:"observations,omitempty"`                                                                   // Parsed observations
	Edges         []*Edge                `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`                                                                                 // Relationships between observations
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Module-specific metadata about the parse
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                                                                                 // Error message if parsing failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_mdemg_module_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{9}
}

func (x *ParseResponse) GetObservations() []*Observation {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *ParseResponse) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *ParseResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ParseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`                                                       // Identifier for the source to sync (e.g., Linear workspace ID)
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`                                                                           // Last sync cursor (empty for full sync)
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Sync configuration (e.g., API keys, filters)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_mdemg_module_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{10}
}

func (x *SyncRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *SyncRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SyncRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observations  []*Observation         `protobuf:"bytes,1,rep,name=observations,proto3" json:"observations,omitempty"`       // New/updated observations
	Edges         []*Edge                `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`                     // New/updated edges
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`                   // Cursor for next incremental sync
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"` // Whether there are more items to sync
	Stats         *SyncStats             `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`                     // Sync statistics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_mdemg_module_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{11}
}

func (x *SyncResponse) GetObservations() []*Observation {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *SyncResponse) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *SyncResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SyncResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SyncResponse) GetStats() *SyncStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type SyncStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemsProcessed int32                  `protobuf:"varint,1,opt,name=items_processed,json=itemsProcessed,proto3" json:"items_processed,omitempty"`
	ItemsCreated   int32                  `protobuf:"varint,2,opt,name=items_created,json=itemsCreated,proto3" json:"items_created,omitempty"`
	ItemsUpdated   int32                  `protobuf:"varint,3,opt,name=items_updated,json=itemsUpdated,proto3" json:"items_updated,omitempty"`
	ItemsSkipped   int32                  `protobuf:"varint,4,opt,name=items_skipped,json=itemsSkipped,proto3" json:"items_skipped,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncStats) Reset() {
	*x = SyncStats{}
	mi := &file_mdemg_module_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStats) ProtoMessage() {}

func (x *SyncStats) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStats.ProtoReflect.Descriptor instead.
func (*SyncStats) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{12}
}

func (x *SyncStats) GetItemsProcessed() int32 {
	if x != nil {
		return x.ItemsProcessed
	}
	return 0
}

func (x *SyncStats) GetItemsCreated() int32 {
	if x != nil {
		return x.ItemsCreated
	}
	return 0
}

func (x *SyncStats) GetItemsUpdated() int32 {
	if x != nil {
		return x.ItemsUpdated
	}
	return 0
}

func (x *SyncStats) GetItemsSkipped() int32 {
	if x != nil {
		return x.ItemsSkipped
	}
	return 0
}

type ProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryText     string                 `protobuf:"bytes,1,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`                                                      // Original query
	Candidates    []*RetrievalCandidate  `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`                                                                     // Candidates to process
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`                                                                    // Number of results to return
	Context       map[string]string      `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_mdemg_module_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{13}
}

func (x *ProcessRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *ProcessRequest) GetCandidates() []*RetrievalCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *ProcessRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *ProcessRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type ProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RetrievalCandidate  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`                                                                             // Processed/reranked results
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Processing metadata (e.g., latency, tokens used)
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                                                                 // Error message if processing failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_mdemg_module_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessResponse) GetResults() []*RetrievalCandidate {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ProcessResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProcessResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RetrievalCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Score         float32                `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`
	VectorSim     float32                `protobuf:"fixed32,6,opt,name=vector_sim,json=vectorSim,proto3" json:"vector_sim,omitempty"`
	Activation    float32                `protobuf:"fixed32,7,opt,name=activation,proto3" json:"activation,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievalCandidate) Reset() {
	*x = RetrievalCandidate{}
	mi := &file_mdemg_module_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalCandidate) ProtoMessage() {}

func (x *RetrievalCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalCandidate.ProtoReflect.Descriptor instead.
func (*RetrievalCandidate) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{15}
}

func (x *RetrievalCandidate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RetrievalCandidate) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RetrievalCandidate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RetrievalCandidate) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *RetrievalCandidate) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RetrievalCandidate) GetVectorSim() float32 {
	if x != nil {
		return x.VectorSim
	}
	return 0
}

func (x *RetrievalCandidate) GetActivation() float32 {
	if x != nil {
		return x.Activation
	}
	return 0
}

func (x *RetrievalCandidate) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                                               // Unique task execution ID
	Trigger       string                 `protobuf:"bytes,2,opt,name=trigger,proto3" json:"trigger,omitempty"`                                                                           // What triggered this execution (e.g., "schedule", "event:ingest")
	Context       map[string]string      `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Execution context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_mdemg_module_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{16}
}

func (x *ExecuteRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteRequest) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *ExecuteRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stats         *ExecuteStats          `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_mdemg_module_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{17}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteResponse) GetStats() *ExecuteStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExecuteStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodesCreated  int32                  `protobuf:"varint,1,opt,name=nodes_created,json=nodesCreated,proto3" json:"nodes_created,omitempty"`
	NodesUpdated  int32                  `protobuf:"varint,2,opt,name=nodes_updated,json=nodesUpdated,proto3" json:"nodes_updated,omitempty"`
	EdgesCreated  int32                  `protobuf:"varint,3,opt,name=edges_created,json=edgesCreated,proto3" json:"edges_created,omitempty"`
	EdgesUpdated  int32                  `protobuf:"varint,4,opt,name=edges_updated,json=edgesUpdated,proto3" json:"edges_updated,omitempty"`
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStats) Reset() {
	*x = ExecuteStats{}
	mi := &file_mdemg_module_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStats) ProtoMessage() {}

func (x *ExecuteStats) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStats.ProtoReflect.Descriptor instead.
func (*ExecuteStats) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{18}
}

func (x *ExecuteStats) GetNodesCreated() int32 {
	if x != nil {
		return x.NodesCreated
	}
	return 0
}

func (x *ExecuteStats) GetNodesUpdated() int32 {
	if x != nil {
		return x.NodesUpdated
	}
	return 0
}

func (x *ExecuteStats) GetEdgesCreated() int32 {
	if x != nil {
		return x.EdgesCreated
	}
	return 0
}

func (x *ExecuteStats) GetEdgesUpdated() int32 {
	if x != nil {
		return x.EdgesUpdated
	}
	return 0
}

func (x *ExecuteStats) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type GetScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleRequest) Reset() {
	*x = GetScheduleRequest{}
	mi := &file_mdemg_module_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleRequest) ProtoMessage() {}

func (x *GetScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleRequest) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{19}
}

type GetScheduleResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CronExpression     string                 `protobuf:"bytes,1,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`                // Cron expression (e.g., "0 * * * *" for hourly)
	EventTriggers      []string               `protobuf:"bytes,2,rep,name=event_triggers,json=eventTriggers,proto3" json:"event_triggers,omitempty"`                   // Events that should trigger execution (e.g., "ingest", "session_end")
	MinIntervalSeconds int32                  `protobuf:"varint,3,opt,name=min_interval_seconds,json=minIntervalSeconds,proto3" json:"min_interval_seconds,omitempty"` // Minimum time between executions
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetScheduleResponse) Reset() {
	*x = GetScheduleResponse{}
	mi := &file_mdemg_module_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleResponse) ProtoMessage() {}

func (x *GetScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleResponse.ProtoReflect.Descriptor instead.
func (*GetScheduleResponse) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{20}
}

func (x *GetScheduleResponse) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *GetScheduleResponse) GetEventTriggers() []string {
	if x != nil {
		return x.EventTriggers
	}
	return nil
}

func (x *GetScheduleResponse) GetMinIntervalSeconds() int32 {
	if x != nil {
		return x.MinIntervalSeconds
	}
	return 0
}

type Observation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                                                 // Optional - generated if not provided
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                                                                                   // Path/URI of the source
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // Human-readable name
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                                                                             // Content text
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`                                                  // Content type (e.g., "code", "task", "note")
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`                                                                                   // Tags for categorization
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	Timestamp     string                 `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                         // ISO8601 timestamp
	Source        string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`                                                                               // Source identifier (e.g., "linear", "obsidian")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_mdemg_module_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{21}
}

func (x *Observation) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Observation) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Observation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Observation) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Observation) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Observation) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Observation) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Observation) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Observation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    string                 `protobuf:"bytes,1,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`                                                       // Source node
	ToNodeId      string                 `protobuf:"bytes,2,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`                                                             // Target node
	RelType       string                 `protobuf:"bytes,3,opt,name=rel_type,json=relType,proto3" json:"rel_type,omitempty"`                                                                  // Relationship type (e.g., "BLOCKS", "RELATED_TO")
	Weight        float32                `protobuf:"fixed32,4,opt,name=weight,proto3" json:"weight,omitempty"`                                                                                 // Edge weight (0.0-1.0)
	Properties    map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional edge properties
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_mdemg_module_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{22}
}

func (x *Edge) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *Edge) GetToNodeId() string {
	if x != nil {
		return x.ToNodeId
	}
	return ""
}

func (x *Edge) GetRelType() string {
	if x != nil {
		return x.RelType
	}
	return ""
}

func (x *Edge) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Edge) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// CRUDEntity represents a generic entity returned by CRUD operations.
type CRUDEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                   // Entity ID in the external system
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`                                                 // Type (e.g., "issue", "project", "comment")
	Fields        map[string]string      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Entity fields as key-value pairs
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                    // ISO8601 creation timestamp
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                    // ISO8601 last update timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRUDEntity) Reset() {
	*x = CRUDEntity{}
	mi := &file_mdemg_module_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRUDEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRUDEntity) ProtoMessage() {}

func (x *CRUDEntity) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRUDEntity.ProtoReflect.Descriptor instead.
func (*CRUDEntity) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{23}
}

func (x *CRUDEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CRUDEntity) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CRUDEntity) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *CRUDEntity) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CRUDEntity) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CRUDCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`                                                 // Required: type of entity to create
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Entity fields (e.g., "title", "description")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRUDCreateRequest) Reset() {
	*x = CRUDCreateRequest{}
	mi := &file_mdemg_module_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRUDCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRUDCreateRequest) ProtoMessage() {}

func (x *CRUDCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRUDCreateRequest.ProtoReflect.Descriptor instead.
func (*CRUDCreateRequest) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{24}
}

func (x *CRUDCreateRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CRUDCreateRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type CRUDCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *CRUDEntity            `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`    // The created entity
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // Whether creation succeeded
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`      // Error message if failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRUDCreateResponse) Reset() {
	*x = CRUDCreateResponse{}
	mi := &file_mdemg_module_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRUDCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRUDCreateResponse) ProtoMessage() {}

func (x *CRUDCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRUDCreateResponse.ProtoReflect.Descriptor instead.
func (*CRUDCreateResponse) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{25}
}

func (x *CRUDCreateResponse) GetEntity() *CRUDEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *CRUDCreateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CRUDCreateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CRUDReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // Required: type of entity
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                   // Required: entity ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRUDReadRequest) Reset() {
	*x = CRUDReadRequest{}
	mi := &file_mdemg_module_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRUDReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRUDReadRequest) ProtoMessage() {}

func (x *CRUDReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRUDReadRequest.ProtoReflect.Descriptor instead.
func (*CRUDReadRequest) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{26}
}

func (x *CRUDReadRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CRUDReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CRUDReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *CRUDEntity            `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"` // The requested entity
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRUDReadResponse) Reset() {
	*x = CRUDReadResponse{}
	mi := &file_mdemg_module_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRUDReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRUDReadResponse) ProtoMessage() {}

func (x *CRUDReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRUDReadResponse.ProtoReflect.Descriptor instead.
func (*CRUDReadResponse) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{27}
}

func (x *CRUDReadResponse) GetEntity() *CRUDEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *CRUDReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CRUDReadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CRUDUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`                                                 // Required: type of entity
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                                                                   // Required: entity ID
	Fields        map[string]string      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Fields to update (partial update)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRUDUpdateRequest) Reset() {
	*x = CRUDUpdateRequest{}
	mi := &file_mdemg_module_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRUDUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRUDUpdateRequest) ProtoMessage() {}

func (x *CRUDUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRUDUpdateRequest.ProtoReflect.Descriptor instead.
func (*CRUDUpdateRequest) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{28}
}

func (x *CRUDUpdateRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CRUDUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CRUDUpdateRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type CRUDUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *CRUDEntity            `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"` // The updated entity
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRUDUpdateResponse) Reset() {
	*x = CRUDUpdateResponse{}
	mi := &file_mdemg_module_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRUDUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRUDUpdateResponse) ProtoMessage() {}

func (x *CRUDUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRUDUpdateResponse.ProtoReflect.Descriptor instead.
func (*CRUDUpdateResponse) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{29}
}

func (x *CRUDUpdateResponse) GetEntity() *CRUDEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *CRUDUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CRUDUpdateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CRUDDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // Required: type of entity
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                   // Required: entity ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRUDDeleteRequest) Reset() {
	*x = CRUDDeleteRequest{}
	mi := &file_mdemg_module_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRUDDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRUDDeleteRequest) ProtoMessage() {}

func (x *CRUDDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRUDDeleteRequest.ProtoReflect.Descriptor instead.
func (*CRUDDeleteRequest) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{30}
}

func (x *CRUDDeleteRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CRUDDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CRUDDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRUDDeleteResponse) Reset() {
	*x = CRUDDeleteResponse{}
	mi := &file_mdemg_module_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRUDDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRUDDeleteResponse) ProtoMessage() {}

func (x *CRUDDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRUDDeleteResponse.ProtoReflect.Descriptor instead.
func (*CRUDDeleteResponse) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{31}
}

func (x *CRUDDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CRUDDeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CRUDListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`                                                   // Required: type of entity to list
	Filters       map[string]string      `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional filters (e.g., "team": "ENG", "state": "in_progress")
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                                                              // Max results (default: 50)
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`                                                                             // Pagination cursor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRUDListRequest) Reset() {
	*x = CRUDListRequest{}
	mi := &file_mdemg_module_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRUDListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRUDListRequest) ProtoMessage() {}

func (x *CRUDListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRUDListRequest.ProtoReflect.Descriptor instead.
func (*CRUDListRequest) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{32}
}

func (x *CRUDListRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CRUDListRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *CRUDListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CRUDListRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type CRUDListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*CRUDEntity          `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`                        // List of entities
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`  // Cursor for next page (empty if no more)
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total matching entities (if available)
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRUDListResponse) Reset() {
	*x = CRUDListResponse{}
	mi := &file_mdemg_module_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRUDListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRUDListResponse) ProtoMessage() {}

func (x *CRUDListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mdemg_module_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRUDListResponse.ProtoReflect.Descriptor instead.
func (*CRUDListResponse) Descriptor() ([]byte, []int) {
	return file_mdemg_module_proto_rawDescGZIP(), []int{33}
}

func (x *CRUDListResponse) GetEntities() []*CRUDEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *CRUDListResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *CRUDListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CRUDListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CRUDListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_mdemg_module_proto protoreflect.FileDescriptor

const file_mdemg_module_proto_rawDesc = "" +
	"\n" +
	"\x12mdemg-module.proto\x12\x0fmdemg.module.v1\"\xda\x01\n" +
	"\x10HandshakeRequest\x12#\n" +
	"\rmdemg_version\x18\x01 \x01(\tR\fmdemgVersion\x12\x1f\n" +
	"\vsocket_path\x18\x02 \x01(\tR\n" +
	"socketPath\x12E\n" +
	"\x06config\x18\x03 \x03(\v2-.mdemg.module.v1.HandshakeRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe5\x01\n" +
	"\x11HandshakeResponse\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12%\n" +
	"\x0emodule_version\x18\x02 \x01(\tR\rmoduleVersion\x12<\n" +
	"\vmodule_type\x18\x03 \x01(\x0e2\x1b.mdemg.module.v1.ModuleTypeR\n" +
	"moduleType\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x14\n" +
	"\x05ready\x18\x05 \x01(\bR\x05ready\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x14\n" +
	"\x12HealthCheckRequest\"\xd0\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12K\n" +
	"\ametrics\x18\x03 \x03(\v21.mdemg.module.v1.HealthCheckResponse.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x0fShutdownRequest\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x01 \x01(\x05R\ttimeoutMs\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"F\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd6\x01\n" +
	"\fMatchRequest\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x01 \x01(\tR\tsourceUri\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12G\n" +
	"\bmetadata\x18\x03 \x03(\v2+.mdemg.module.v1.MatchRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\rMatchResponse\x12\x18\n" +
	"\amatches\x18\x01 \x01(\bR\amatches\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xf0\x01\n" +
	"\fParseRequest\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x01 \x01(\tR\tsourceUri\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12G\n" +
	"\bmetadata\x18\x04 \x03(\v2+.mdemg.module.v1.ParseRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x02\n" +
	"\rParseResponse\x12@\n" +
	"\fobservations\x18\x01 \x03(\v2\x1c.mdemg.module.v1.ObservationR\fobservations\x12+\n" +
	"\x05edges\x18\x02 \x03(\v2\x15.mdemg.module.v1.EdgeR\x05edges\x12H\n" +
	"\bmetadata\x18\x03 \x03(\v2,.mdemg.module.v1.ParseResponse.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbf\x01\n" +
	"\vSyncRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12@\n" +
	"\x06config\x18\x03 \x03(\v2(.mdemg.module.v1.SyncRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe2\x01\n" +
	"\fSyncResponse\x12@\n" +
	"\fobservations\x18\x01 \x03(\v2\x1c.mdemg.module.v1.ObservationR\fobservations\x12+\n" +
	"\x05edges\x18\x02 \x03(\v2\x15.mdemg.module.v1.EdgeR\x05edges\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\x120\n" +
	"\x05stats\x18\x05 \x01(\v2\x1a.mdemg.module.v1.SyncStatsR\x05stats\"\xa3\x01\n" +
	"\tSyncStats\x12'\n" +
	"\x0fitems_processed\x18\x01 \x01(\x05R\x0eitemsProcessed\x12#\n" +
	"\ritems_created\x18\x02 \x01(\x05R\fitemsCreated\x12#\n" +
	"\ritems_updated\x18\x03 \x01(\x05R\fitemsUpdated\x12#\n" +
	"\ritems_skipped\x18\x04 \x01(\x05R\fitemsSkipped\"\x8d\x02\n" +
	"\x0eProcessRequest\x12\x1d\n" +
	"\n" +
	"query_text\x18\x01 \x01(\tR\tqueryText\x12C\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2#.mdemg.module.v1.RetrievalCandidateR\n" +
	"candidates\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12F\n" +
	"\acontext\x18\x04 \x03(\v2,.mdemg.module.v1.ProcessRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x01\n" +
	"\x0fProcessResponse\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.mdemg.module.v1.RetrievalCandidateR\aresults\x12J\n" +
	"\bmetadata\x18\x02 \x03(\v2..mdemg.module.v1.ProcessResponse.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x02\n" +
	"\x12RetrievalCandidate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x02R\x05score\x12\x1d\n" +
	"\n" +
	"vector_sim\x18\x06 \x01(\x02R\tvectorSim\x12\x1e\n" +
	"\n" +
	"activation\x18\a \x01(\x02R\n" +
	"activation\x12M\n" +
	"\bmetadata\x18\b \x03(\v21.mdemg.module.v1.RetrievalCandidate.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x01\n" +
	"\x0eExecuteRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\atrigger\x18\x02 \x01(\tR\atrigger\x12F\n" +
	"\acontext\x18\x03 \x03(\v2,.mdemg.module.v1.ExecuteRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x05stats\x18\x03 \x01(\v2\x1d.mdemg.module.v1.ExecuteStatsR\x05stats\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xc3\x01\n" +
	"\fExecuteStats\x12#\n" +
	"\rnodes_created\x18\x01 \x01(\x05R\fnodesCreated\x12#\n" +
	"\rnodes_updated\x18\x02 \x01(\x05R\fnodesUpdated\x12#\n" +
	"\redges_created\x18\x03 \x01(\x05R\fedgesCreated\x12#\n" +
	"\redges_updated\x18\x04 \x01(\x05R\fedgesUpdated\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\"\x14\n" +
	"\x12GetScheduleRequest\"\x97\x01\n" +
	"\x13GetScheduleResponse\x12'\n" +
	"\x0fcron_expression\x18\x01 \x01(\tR\x0ecronExpression\x12%\n" +
	"\x0eevent_triggers\x18\x02 \x03(\tR\reventTriggers\x120\n" +
	"\x14min_interval_seconds\x18\x03 \x01(\x05R\x12minIntervalSeconds\"\xda\x02\n" +
	"\vObservation\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12F\n" +
	"\bmetadata\x18\a \x03(\v2*.mdemg.module.v1.Observation.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x01\n" +
	"\x04Edge\x12 \n" +
	"\ffrom_node_id\x18\x01 \x01(\tR\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x02 \x01(\tR\btoNodeId\x12\x19\n" +
	"\brel_type\x18\x03 \x01(\tR\arelType\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x02R\x06weight\x12E\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2%.mdemg.module.v1.Edge.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf7\x01\n" +
	"\n" +
	"CRUDEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12?\n" +
	"\x06fields\x18\x03 \x03(\v2'.mdemg.module.v1.CRUDEntity.FieldsEntryR\x06fields\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\x11CRUDCreateRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12F\n" +
	"\x06fields\x18\x02 \x03(\v2..mdemg.module.v1.CRUDCreateRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x12CRUDCreateResponse\x123\n" +
	"\x06entity\x18\x01 \x01(\v2\x1b.mdemg.module.v1.CRUDEntityR\x06entity\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"B\n" +
	"\x0fCRUDReadRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"w\n" +
	"\x10CRUDReadResponse\x123\n" +
	"\x06entity\x18\x01 \x01(\v2\x1b.mdemg.module.v1.CRUDEntityR\x06entity\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xc7\x01\n" +
	"\x11CRUDUpdateRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12F\n" +
	"\x06fields\x18\x03 \x03(\v2..mdemg.module.v1.CRUDUpdateRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x12CRUDUpdateResponse\x123\n" +
	"\x06entity\x18\x01 \x01(\v2\x1b.mdemg.module.v1.CRUDEntityR\x06entity\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"D\n" +
	"\x11CRUDDeleteRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"D\n" +
	"\x12CRUDDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xe5\x01\n" +
	"\x0fCRUDListRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12G\n" +
	"\afilters\x18\x02 \x03(\v2-.mdemg.module.v1.CRUDListRequest.FiltersEntryR\afilters\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\x10CRUDListResponse\x127\n" +
	"\bentities\x18\x01 \x03(\v2\x1b.mdemg.module.v1.CRUDEntityR\bentities\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error*\x8a\x01\n" +
	"\n" +
	"ModuleType\x12\x1b\n" +
	"\x17MODULE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MODULE_TYPE_INGESTION\x10\x01\x12\x19\n" +
	"\x15MODULE_TYPE_REASONING\x10\x02\x12\x13\n" +
	"\x0fMODULE_TYPE_APE\x10\x03\x12\x14\n" +
	"\x10MODULE_TYPE_CRUD\x10\x042\x90\x02\n" +
	"\x0fModuleLifecycle\x12R\n" +
	"\tHandshake\x12!.mdemg.module.v1.HandshakeRequest\x1a\".mdemg.module.v1.HandshakeResponse\x12X\n" +
	"\vHealthCheck\x12#.mdemg.module.v1.HealthCheckRequest\x1a$.mdemg.module.v1.HealthCheckResponse\x12O\n" +
	"\bShutdown\x12 .mdemg.module.v1.ShutdownRequest\x1a!.mdemg.module.v1.ShutdownResponse2\xea\x01\n" +
	"\x0fIngestionModule\x12H\n" +
	"\aMatches\x12\x1d.mdemg.module.v1.MatchRequest\x1a\x1e.mdemg.module.v1.MatchResponse\x12F\n" +
	"\x05Parse\x12\x1d.mdemg.module.v1.ParseRequest\x1a\x1e.mdemg.module.v1.ParseResponse\x12E\n" +
	"\x04Sync\x12\x1c.mdemg.module.v1.SyncRequest\x1a\x1d.mdemg.module.v1.SyncResponse0\x012_\n" +
	"\x0fReasoningModule\x12L\n" +
	"\aProcess\x12\x1f.mdemg.module.v1.ProcessRequest\x1a .mdemg.module.v1.ProcessResponse2\xb3\x01\n" +
	"\tAPEModule\x12L\n" +
	"\aExecute\x12\x1f.mdemg.module.v1.ExecuteRequest\x1a .mdemg.module.v1.ExecuteResponse\x12X\n" +
	"\vGetSchedule\x12#.mdemg.module.v1.GetScheduleRequest\x1a$.mdemg.module.v1.GetScheduleResponse2\x9f\x03\n" +
	"\n" +
	"CRUDModule\x12Q\n" +
	"\x06Create\x12\".mdemg.module.v1.CRUDCreateRequest\x1a#.mdemg.module.v1.CRUDCreateResponse\x12K\n" +
	"\x04Read\x12 .mdemg.module.v1.CRUDReadRequest\x1a!.mdemg.module.v1.CRUDReadResponse\x12Q\n" +
	"\x06Update\x12\".mdemg.module.v1.CRUDUpdateRequest\x1a#.mdemg.module.v1.CRUDUpdateResponse\x12Q\n" +
	"\x06Delete\x12\".mdemg.module.v1.CRUDDeleteRequest\x1a#.mdemg.module.v1.CRUDDeleteResponse\x12K\n" +
	"\x04List\x12 .mdemg.module.v1.CRUDListRequest\x1a!.mdemg.module.v1.CRUDListResponseB\x14Z\x12mdemg/api/modulepbb\x06proto3"

var (
	file_mdemg_module_proto_rawDescOnce sync.Once
	file_mdemg_module_proto_rawDescData []byte
)

func file_mdemg_module_proto_rawDescGZIP() []byte {
	file_mdemg_module_proto_rawDescOnce.Do(func() {
		file_mdemg_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mdemg_module_proto_rawDesc), len(file_mdemg_module_proto_rawDesc)))
	})
	return file_mdemg_module_proto_rawDescData
}

var file_mdemg_module_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mdemg_module_proto_msgTypes = make([]protoimpl.MessageInfo, 50)
var file_mdemg_module_proto_goTypes = []any{
	(ModuleType)(0),             // 0: mdemg.module.v1.ModuleType
	(*HandshakeRequest)(nil),    // 1: mdemg.module.v1.HandshakeRequest
	(*HandshakeResponse)(nil),   // 2: mdemg.module.v1.HandshakeResponse
	(*HealthCheckRequest)(nil),  // 3: mdemg.module.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 4: mdemg.module.v1.HealthCheckResponse
	(*ShutdownRequest)(nil),     // 5: mdemg.module.v1.ShutdownRequest
	(*ShutdownResponse)(nil),    // 6: mdemg.module.v1.ShutdownResponse
	(*MatchRequest)(nil),        // 7: mdemg.module.v1.MatchRequest
	(*MatchResponse)(nil),       // 8: mdemg.module.v1.MatchResponse
	(*ParseRequest)(nil),        // 9: mdemg.module.v1.ParseRequest
	(*ParseResponse)(nil),       // 10: mdemg.module.v1.ParseResponse
	(*SyncRequest)(nil),         // 11: mdemg.module.v1.SyncRequest
	(*SyncResponse)(nil),        // 12: mdemg.module.v1.SyncResponse
	(*SyncStats)(nil),           // 13: mdemg.module.v1.SyncStats
	(*ProcessRequest)(nil),      // 14: mdemg.module.v1.ProcessRequest
	(*ProcessResponse)(nil),     // 15: mdemg.module.v1.ProcessResponse
	(*RetrievalCandidate)(nil),  // 16: mdemg.module.v1.RetrievalCandidate
	(*ExecuteRequest)(nil),      // 17: mdemg.module.v1.ExecuteRequest
	(*ExecuteResponse)(nil),     // 18: mdemg.module.v1.ExecuteResponse
	(*ExecuteStats)(nil),        // 19: mdemg.module.v1.ExecuteStats
	(*GetScheduleRequest)(nil),  // 20: mdemg.module.v1.GetScheduleRequest
	(*GetScheduleResponse)(nil), // 21: mdemg.module.v1.GetScheduleResponse
	(*Observation)(nil),         // 22: mdemg.module.v1.Observation
	(*Edge)(nil),                // 23: mdemg.module.v1.Edge
	(*CRUDEntity)(nil),          // 24: mdemg.module.v1.CRUDEntity
	(*CRUDCreateRequest)(nil),   // 25: mdemg.module.v1.CRUDCreateRequest
	(*CRUDCreateResponse)(nil),  // 26: mdemg.module.v1.CRUDCreateResponse
	(*CRUDReadRequest)(nil),     // 27: mdemg.module.v1.CRUDReadRequest
	(*CRUDReadResponse)(nil),    // 28: mdemg.module.v1.CRUDReadResponse
	(*CRUDUpdateRequest)(nil),   // 29: mdemg.module.v1.CRUDUpdateRequest
	(*CRUDUpdateResponse)(nil),  // 30: mdemg.module.v1.CRUDUpdateResponse
	(*CRUDDeleteRequest)(nil),   // 31: mdemg.module.v1.CRUDDeleteRequest
	(*CRUDDeleteResponse)(nil),  // 32: mdemg.module.v1.CRUDDeleteResponse
	(*CRUDListRequest)(nil),     // 33: mdemg.module.v1.CRUDListRequest
	(*CRUDListResponse)(nil),    // 34: mdemg.module.v1.CRUDListResponse
	nil,                         // 35: mdemg.module.v1.HandshakeRequest.ConfigEntry
	nil,                         // 36: mdemg.module.v1.HealthCheckResponse.MetricsEntry
	nil,                         // 37: mdemg.module.v1.MatchRequest.MetadataEntry
	nil,                         // 38: mdemg.module.v1.ParseRequest.MetadataEntry
	nil,                         // 39: mdemg.module.v1.ParseResponse.MetadataEntry
	nil,                         // 40: mdemg.module.v1.SyncRequest.ConfigEntry
	nil,                         // 41: mdemg.module.v1.ProcessRequest.ContextEntry
	nil,                         // 42: mdemg.module.v1.ProcessResponse.MetadataEntry
	nil,                         // 43: mdemg.module.v1.RetrievalCandidate.MetadataEntry
	nil,                         // 44: mdemg.module.v1.ExecuteRequest.ContextEntry
	nil,                         // 45: mdemg.module.v1.Observation.MetadataEntry
	nil,                         // 46: mdemg.module.v1.Edge.PropertiesEntry
	nil,                         // 47: mdemg.module.v1.CRUDEntity.FieldsEntry
	nil,                         // 48: mdemg.module.v1.CRUDCreateRequest.FieldsEntry
	nil,                         // 49: mdemg.module.v1.CRUDUpdateRequest.FieldsEntry
	nil,                         // 50: mdemg.module.v1.CRUDListRequest.FiltersEntry
}
var file_mdemg_module_proto_depIdxs = []int32{
	35, // 0: mdemg.module.v1.HandshakeRequest.config:type_name -> mdemg.module.v1.HandshakeRequest.ConfigEntry
	0,  // 1: mdemg.module.v1.HandshakeResponse.module_type:type_name -> mdemg.module.v1.ModuleType
	36, // 2: mdemg.module.v1.HealthCheckResponse.metrics:type_name -> mdemg.module.v1.HealthCheckResponse.MetricsEntry
	37, // 3: mdemg.module.v1.MatchRequest.metadata:type_name -> mdemg.module.v1.MatchRequest.MetadataEntry
	38, // 4: mdemg.module.v1.ParseRequest.metadata:type_name -> mdemg.module.v1.ParseRequest.MetadataEntry
	22, // 5: mdemg.module.v1.ParseResponse.observations:type_name -> mdemg.module.v1.Observation
	23, // 6: mdemg.module.v1.ParseResponse.edges:type_name -> mdemg.module.v1.Edge
	39, // 7: mdemg.module.v1.ParseResponse.metadata:type_name -> mdemg.module.v1.ParseResponse.MetadataEntry
	40, // 8: mdemg.module.v1.SyncRequest.config:type_name -> mdemg.module.v1.SyncRequest.ConfigEntry
	22, // 9: mdemg.module.v1.SyncResponse.observations:type_name -> mdemg.module.v1.Observation
	23, // 10: mdemg.module.v1.SyncResponse.edges:type_name -> mdemg.module.v1.Edge
	13, // 11: mdemg.module.v1.SyncResponse.stats:type_name -> mdemg.module.v1.SyncStats
	16, // 12: mdemg.module.v1.ProcessRequest.candidates:type_name -> mdemg.module.v1.RetrievalCandidate
	41, // 13: mdemg.module.v1.ProcessRequest.context:type_name -> mdemg.module.v1.ProcessRequest.ContextEntry
	16, // 14: mdemg.module.v1.ProcessResponse.results:type_name -> mdemg.module.v1.RetrievalCandidate
	42, // 15: mdemg.module.v1.ProcessResponse.metadata:type_name -> mdemg.module.v1.ProcessResponse.MetadataEntry
	43, // 16: mdemg.module.v1.RetrievalCandidate.metadata:type_name -> mdemg.module.v1.RetrievalCandidate.MetadataEntry
	44, // 17: mdemg.module.v1.ExecuteRequest.context:type_name -> mdemg.module.v1.ExecuteRequest.ContextEntry
	19, // 18: mdemg.module.v1.ExecuteResponse.stats:type_name -> mdemg.module.v1.ExecuteStats
	45, // 19: mdemg.module.v1.Observation.metadata:type_name -> mdemg.module.v1.Observation.MetadataEntry
	46, // 20: mdemg.module.v1.Edge.properties:type_name -> mdemg.module.v1.Edge.PropertiesEntry
	47, // 21: mdemg.module.v1.CRUDEntity.fields:type_name -> mdemg.module.v1.CRUDEntity.FieldsEntry
	48, // 22: mdemg.module.v1.CRUDCreateRequest.fields:type_name -> mdemg.module.v1.CRUDCreateRequest.FieldsEntry
	24, // 23: mdemg.module.v1.CRUDCreateResponse.entity:type_name -> mdemg.module.v1.CRUDEntity
	24, // 24: mdemg.module.v1.CRUDReadResponse.entity:type_name -> mdemg.module.v1.CRUDEntity
	49, // 25: mdemg.module.v1.CRUDUpdateRequest.fields:type_name -> mdemg.module.v1.CRUDUpdateRequest.FieldsEntry
	24, // 26: mdemg.module.v1.CRUDUpdateResponse.entity:type_name -> mdemg.module.v1.CRUDEntity
	50, // 27: mdemg.module.v1.CRUDListRequest.filters:type_name -> mdemg.module.v1.CRUDListRequest.FiltersEntry
	24, // 28: mdemg.module.v1.CRUDListResponse.entities:type_name -> mdemg.module.v1.CRUDEntity
	1,  // 29: mdemg.module.v1.ModuleLifecycle.Handshake:input_type -> mdemg.module.v1.HandshakeRequest
	3,  // 30: mdemg.module.v1.ModuleLifecycle.HealthCheck:input_type -> mdemg.module.v1.HealthCheckRequest
	5,  // 31: mdemg.module.v1.ModuleLifecycle.Shutdown:input_type -> mdemg.module.v1.ShutdownRequest
	7,  // 32: mdemg.module.v1.IngestionModule.Matches:input_type -> mdemg.module.v1.MatchRequest
	9,  // 33: mdemg.module.v1.IngestionModule.Parse:input_type -> mdemg.module.v1.ParseRequest
	11, // 34: mdemg.module.v1.IngestionModule.Sync:input_type -> mdemg.module.v1.SyncRequest
	14, // 35: mdemg.module.v1.ReasoningModule.Process:input_type -> mdemg.module.v1.ProcessRequest
	17, // 36: mdemg.module.v1.APEModule.Execute:input_type -> mdemg.module.v1.ExecuteRequest
	20, // 37: mdemg.module.v1.APEModule.GetSchedule:input_type -> mdemg.module.v1.GetScheduleRequest
	25, // 38: mdemg.module.v1.CRUDModule.Create:input_type -> mdemg.module.v1.CRUDCreateRequest
	27, // 39: mdemg.module.v1.CRUDModule.Read:input_type -> mdemg.module.v1.CRUDReadRequest
	29, // 40: mdemg.module.v1.CRUDModule.Update:input_type -> mdemg.module.v1.CRUDUpdateRequest
	31, // 41: mdemg.module.v1.CRUDModule.Delete:input_type -> mdemg.module.v1.CRUDDeleteRequest
	33, // 42: mdemg.module.v1.CRUDModule.List:input_type -> mdemg.module.v1.CRUDListRequest
	2,  // 43: mdemg.module.v1.ModuleLifecycle.Handshake:output_type -> mdemg.module.v1.HandshakeResponse
	4,  // 44: mdemg.module.v1.ModuleLifecycle.HealthCheck:output_type -> mdemg.module.v1.HealthCheckResponse
	6,  // 45: mdemg.module.v1.ModuleLifecycle.Shutdown:output_type -> mdemg.module.v1.ShutdownResponse
	8,  // 46: mdemg.module.v1.IngestionModule.Matches:output_type -> mdemg.module.v1.MatchResponse
	10, // 47: mdemg.module.v1.IngestionModule.Parse:output_type -> mdemg.module.v1.ParseResponse
	12, // 48: mdemg.module.v1.IngestionModule.Sync:output_type -> mdemg.module.v1.SyncResponse
	15, // 49: mdemg.module.v1.ReasoningModule.Process:output_type -> mdemg.module.v1.ProcessResponse
	18, // 50: mdemg.module.v1.APEModule.Execute:output_type -> mdemg.module.v1.ExecuteResponse
	21, // 51: mdemg.module.v1.APEModule.GetSchedule:output_type -> mdemg.module.v1.GetScheduleResponse
	26, // 52: mdemg.module.v1.CRUDModule.Create:output_type -> mdemg.module.v1.CRUDCreateResponse
	28, // 53: mdemg.module.v1.CRUDModule.Read:output_type -> mdemg.module.v1.CRUDReadResponse
	30, // 54: mdemg.module.v1.CRUDModule.Update:output_type -> mdemg.module.v1.CRUDUpdateResponse
	32, // 55: mdemg.module.v1.CRUDModule.Delete:output_type -> mdemg.module.v1.CRUDDeleteResponse
	34, // 56: mdemg.module.v1.CRUDModule.List:output_type -> mdemg.module.v1.CRUDListResponse
	43, // [43:57] is the sub-list for method output_type
	29, // [29:43] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_mdemg_module_proto_init() }
func file_mdemg_module_proto_init() {
	if File_mdemg_module_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mdemg_module_proto_rawDesc), len(file_mdemg_module_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   50,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_mdemg_module_proto_goTypes,
		DependencyIndexes: file_mdemg_module_proto_depIdxs,
		EnumInfos:         file_mdemg_module_proto_enumTypes,
		MessageInfos:      file_mdemg_module_proto_msgTypes,
	}.Build()
	File_mdemg_module_proto = out.File
	file_mdemg_module_proto_goTypes = nil
	file_mdemg_module_proto_depIdxs = nil
}
