// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: mdemg-module.proto

package modulepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModuleLifecycle_Handshake_FullMethodName   = "/mdemg.module.v1.ModuleLifecycle/Handshake"
	ModuleLifecycle_HealthCheck_FullMethodName = "/mdemg.module.v1.ModuleLifecycle/HealthCheck"
	ModuleLifecycle_Shutdown_FullMethodName    = "/mdemg.module.v1.ModuleLifecycle/Shutdown"
)

// ModuleLifecycleClient is the client API for ModuleLifecycle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModuleLifecycleClient interface {
	// Handshake is called immediately after spawn to verify module is ready.
	// MDEMG sends its version and the socket path; module responds with capabilities.
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// HealthCheck is called periodically (configurable interval, default 5s).
	// Module should respond quickly (<100ms) with current health status.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Shutdown is called when MDEMG is stopping or the module is being disabled.
	// Module should clean up resources and exit gracefully within timeout.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type moduleLifecycleClient struct {
	cc grpc.ClientConnInterface
}

func NewModuleLifecycleClient(cc grpc.ClientConnInterface) ModuleLifecycleClient {
	return &moduleLifecycleClient{cc}
}

func (c *moduleLifecycleClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, ModuleLifecycle_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleLifecycleClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ModuleLifecycle_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleLifecycleClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, ModuleLifecycle_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleLifecycleServer is the server API for ModuleLifecycle service.
// All implementations must embed UnimplementedModuleLifecycleServer
// for forward compatibility.
type ModuleLifecycleServer interface {
	// Handshake is called immediately after spawn to verify module is ready.
	// MDEMG sends its version and the socket path; module responds with capabilities.
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// HealthCheck is called periodically (configurable interval, default 5s).
	// Module should respond quickly (<100ms) with current health status.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Shutdown is called when MDEMG is stopping or the module is being disabled.
	// Module should clean up resources and exit gracefully within timeout.
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedModuleLifecycleServer()
}

// UnimplementedModuleLifecycleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModuleLifecycleServer struct{}

func (UnimplementedModuleLifecycleServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedModuleLifecycleServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedModuleLifecycleServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedModuleLifecycleServer) mustEmbedUnimplementedModuleLifecycleServer() {}
func (UnimplementedModuleLifecycleServer) testEmbeddedByValue()                         {}

// UnsafeModuleLifecycleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModuleLifecycleServer will
// result in compilation errors.
type UnsafeModuleLifecycleServer interface {
	mustEmbedUnimplementedModuleLifecycleServer()
}

func RegisterModuleLifecycleServer(s grpc.ServiceRegistrar, srv ModuleLifecycleServer) {
	// If the following call panics, it indicates UnimplementedModuleLifecycleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModuleLifecycle_ServiceDesc, srv)
}

func _ModuleLifecycle_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleLifecycleServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleLifecycle_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleLifecycleServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleLifecycle_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleLifecycleServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleLifecycle_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleLifecycleServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleLifecycle_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleLifecycleServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleLifecycle_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleLifecycleServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModuleLifecycle_ServiceDesc is the grpc.ServiceDesc for ModuleLifecycle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModuleLifecycle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mdemg.module.v1.ModuleLifecycle",
	HandlerType: (*ModuleLifecycleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _ModuleLifecycle_Handshake_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ModuleLifecycle_HealthCheck_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _ModuleLifecycle_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mdemg-module.proto",
}

const (
	IngestionModule_Matches_FullMethodName = "/mdemg.module.v1.IngestionModule/Matches"
	IngestionModule_Parse_FullMethodName   = "/mdemg.module.v1.IngestionModule/Parse"
	IngestionModule_Sync_FullMethodName    = "/mdemg.module.v1.IngestionModule/Sync"
)

// IngestionModuleClient is the client API for IngestionModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngestionModuleClient interface {
	// Matches checks if this module can handle the given source.
	// Called during ingest to find the right parser.
	Matches(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error)
	// Parse converts source content into MDEMG observations.
	// Called when Matches returns true.
	Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error)
	// Sync performs incremental synchronization with an external source.
	// Called by scheduled jobs or manual sync commands.
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncResponse], error)
}

type ingestionModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestionModuleClient(cc grpc.ClientConnInterface) IngestionModuleClient {
	return &ingestionModuleClient{cc}
}

func (c *ingestionModuleClient) Matches(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, IngestionModule_Matches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestionModuleClient) Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseResponse)
	err := c.cc.Invoke(ctx, IngestionModule_Parse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestionModuleClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestionModule_ServiceDesc.Streams[0], IngestionModule_Sync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncRequest, SyncResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionModule_SyncClient = grpc.ServerStreamingClient[SyncResponse]

// IngestionModuleServer is the server API for IngestionModule service.
// All implementations must embed UnimplementedIngestionModuleServer
// for forward compatibility.
type IngestionModuleServer interface {
	// Matches checks if this module can handle the given source.
	// Called during ingest to find the right parser.
	Matches(context.Context, *MatchRequest) (*MatchResponse, error)
	// Parse converts source content into MDEMG observations.
	// Called when Matches returns true.
	Parse(context.Context, *ParseRequest) (*ParseResponse, error)
	// Sync performs incremental synchronization with an external source.
	// Called by scheduled jobs or manual sync commands.
	Sync(*SyncRequest, grpc.ServerStreamingServer[SyncResponse]) error
	mustEmbedUnimplementedIngestionModuleServer()
}

// UnimplementedIngestionModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestionModuleServer struct{}

func (UnimplementedIngestionModuleServer) Matches(context.Context, *MatchRequest) (*MatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Matches not implemented")
}
func (UnimplementedIngestionModuleServer) Parse(context.Context, *ParseRequest) (*ParseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedIngestionModuleServer) Sync(*SyncRequest, grpc.ServerStreamingServer[SyncResponse]) error {
	return status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedIngestionModuleServer) mustEmbedUnimplementedIngestionModuleServer() {}
func (UnimplementedIngestionModuleServer) testEmbeddedByValue()                         {}

// UnsafeIngestionModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestionModuleServer will
// result in compilation errors.
type UnsafeIngestionModuleServer interface {
	mustEmbedUnimplementedIngestionModuleServer()
}

func RegisterIngestionModuleServer(s grpc.ServiceRegistrar, srv IngestionModuleServer) {
	// If the following call panics, it indicates UnimplementedIngestionModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestionModule_ServiceDesc, srv)
}

func _IngestionModule_Matches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionModuleServer).Matches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionModule_Matches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionModuleServer).Matches(ctx, req.(*MatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestionModule_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionModuleServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionModule_Parse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionModuleServer).Parse(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestionModule_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IngestionModuleServer).Sync(m, &grpc.GenericServerStream[SyncRequest, SyncResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionModule_SyncServer = grpc.ServerStreamingServer[SyncResponse]

// IngestionModule_ServiceDesc is the grpc.ServiceDesc for IngestionModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestionModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mdemg.module.v1.IngestionModule",
	HandlerType: (*IngestionModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Matches",
			Handler:    _IngestionModule_Matches_Handler,
		},
		{
			MethodName: "Parse",
			Handler:    _IngestionModule_Parse_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _IngestionModule_Sync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mdemg-module.proto",
}

const (
	ReasoningModule_Process_FullMethodName = "/mdemg.module.v1.ReasoningModule/Process"
)

// ReasoningModuleClient is the client API for ReasoningModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReasoningModuleClient interface {
	// Process takes retrieval candidates and returns refined results.
	// Called during retrieval pipeline after initial scoring.
	Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error)
}

type reasoningModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewReasoningModuleClient(cc grpc.ClientConnInterface) ReasoningModuleClient {
	return &reasoningModuleClient{cc}
}

func (c *reasoningModuleClient) Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, ReasoningModule_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReasoningModuleServer is the server API for ReasoningModule service.
// All implementations must embed UnimplementedReasoningModuleServer
// for forward compatibility.
type ReasoningModuleServer interface {
	// Process takes retrieval candidates and returns refined results.
	// Called during retrieval pipeline after initial scoring.
	Process(context.Context, *ProcessRequest) (*ProcessResponse, error)
	mustEmbedUnimplementedReasoningModuleServer()
}

// UnimplementedReasoningModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReasoningModuleServer struct{}

func (UnimplementedReasoningModuleServer) Process(context.Context, *ProcessRequest) (*ProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedReasoningModuleServer) mustEmbedUnimplementedReasoningModuleServer() {}
func (UnimplementedReasoningModuleServer) testEmbeddedByValue()                         {}

// UnsafeReasoningModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReasoningModuleServer will
// result in compilation errors.
type UnsafeReasoningModuleServer interface {
	mustEmbedUnimplementedReasoningModuleServer()
}

func RegisterReasoningModuleServer(s grpc.ServiceRegistrar, srv ReasoningModuleServer) {
	// If the following call panics, it indicates UnimplementedReasoningModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReasoningModule_ServiceDesc, srv)
}

func _ReasoningModule_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningModuleServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningModule_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningModuleServer).Process(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReasoningModule_ServiceDesc is the grpc.ServiceDesc for ReasoningModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReasoningModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mdemg.module.v1.ReasoningModule",
	HandlerType: (*ReasoningModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _ReasoningModule_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mdemg-module.proto",
}

const (
	APEModule_Execute_FullMethodName     = "/mdemg.module.v1.APEModule/Execute"
	APEModule_GetSchedule_FullMethodName = "/mdemg.module.v1.APEModule/GetSchedule"
)

// APEModuleClient is the client API for APEModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APEModuleClient interface {
	// Execute runs a background task.
	// Called by scheduler or event triggers.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// GetSchedule returns the module's preferred execution schedule.
	GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*GetScheduleResponse, error)
}

type aPEModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewAPEModuleClient(cc grpc.ClientConnInterface) APEModuleClient {
	return &aPEModuleClient{cc}
}

func (c *aPEModuleClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, APEModule_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPEModuleClient) GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*GetScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScheduleResponse)
	err := c.cc.Invoke(ctx, APEModule_GetSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APEModuleServer is the server API for APEModule service.
// All implementations must embed UnimplementedAPEModuleServer
// for forward compatibility.
type APEModuleServer interface {
	// Execute runs a background task.
	// Called by scheduler or event triggers.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// GetSchedule returns the module's preferred execution schedule.
	GetSchedule(context.Context, *GetScheduleRequest) (*GetScheduleResponse, error)
	mustEmbedUnimplementedAPEModuleServer()
}

// UnimplementedAPEModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPEModuleServer struct{}

func (UnimplementedAPEModuleServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedAPEModuleServer) GetSchedule(context.Context, *GetScheduleRequest) (*GetScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchedule not implemented")
}
func (UnimplementedAPEModuleServer) mustEmbedUnimplementedAPEModuleServer() {}
func (UnimplementedAPEModuleServer) testEmbeddedByValue()                   {}

// UnsafeAPEModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APEModuleServer will
// result in compilation errors.
type UnsafeAPEModuleServer interface {
	mustEmbedUnimplementedAPEModuleServer()
}

func RegisterAPEModuleServer(s grpc.ServiceRegistrar, srv APEModuleServer) {
	// If the following call panics, it indicates UnimplementedAPEModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&APEModule_ServiceDesc, srv)
}

func _APEModule_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APEModuleServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APEModule_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APEModuleServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APEModule_GetSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APEModuleServer).GetSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APEModule_GetSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APEModuleServer).GetSchedule(ctx, req.(*GetScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// APEModule_ServiceDesc is the grpc.ServiceDesc for APEModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APEModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mdemg.module.v1.APEModule",
	HandlerType: (*APEModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _APEModule_Execute_Handler,
		},
		{
			MethodName: "GetSchedule",
			Handler:    _APEModule_GetSchedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mdemg-module.proto",
}

const (
	CRUDModule_Create_FullMethodName = "/mdemg.module.v1.CRUDModule/Create"
	CRUDModule_Read_FullMethodName   = "/mdemg.module.v1.CRUDModule/Read"
	CRUDModule_Update_FullMethodName = "/mdemg.module.v1.CRUDModule/Update"
	CRUDModule_Delete_FullMethodName = "/mdemg.module.v1.CRUDModule/Delete"
	CRUDModule_List_FullMethodName   = "/mdemg.module.v1.CRUDModule/List"
)

// CRUDModuleClient is the client API for CRUDModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CRUDModuleClient interface {
	// Create a new entity in the external system.
	Create(ctx context.Context, in *CRUDCreateRequest, opts ...grpc.CallOption) (*CRUDCreateResponse, error)
	// Read a single entity by ID.
	Read(ctx context.Context, in *CRUDReadRequest, opts ...grpc.CallOption) (*CRUDReadResponse, error)
	// Update an existing entity (partial update via fields map).
	Update(ctx context.Context, in *CRUDUpdateRequest, opts ...grpc.CallOption) (*CRUDUpdateResponse, error)
	// Delete (or archive) an entity by ID.
	Delete(ctx context.Context, in *CRUDDeleteRequest, opts ...grpc.CallOption) (*CRUDDeleteResponse, error)
	// List entities with optional filtering.
	List(ctx context.Context, in *CRUDListRequest, opts ...grpc.CallOption) (*CRUDListResponse, error)
}

type cRUDModuleClient struct {
	cc grpc.ClientConnInterface
}

func NewCRUDModuleClient(cc grpc.ClientConnInterface) CRUDModuleClient {
	return &cRUDModuleClient{cc}
}

func (c *cRUDModuleClient) Create(ctx context.Context, in *CRUDCreateRequest, opts ...grpc.CallOption) (*CRUDCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CRUDCreateResponse)
	err := c.cc.Invoke(ctx, CRUDModule_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRUDModuleClient) Read(ctx context.Context, in *CRUDReadRequest, opts ...grpc.CallOption) (*CRUDReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CRUDReadResponse)
	err := c.cc.Invoke(ctx, CRUDModule_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRUDModuleClient) Update(ctx context.Context, in *CRUDUpdateRequest, opts ...grpc.CallOption) (*CRUDUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CRUDUpdateResponse)
	err := c.cc.Invoke(ctx, CRUDModule_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRUDModuleClient) Delete(ctx context.Context, in *CRUDDeleteRequest, opts ...grpc.CallOption) (*CRUDDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CRUDDeleteResponse)
	err := c.cc.Invoke(ctx, CRUDModule_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRUDModuleClient) List(ctx context.Context, in *CRUDListRequest, opts ...grpc.CallOption) (*CRUDListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CRUDListResponse)
	err := c.cc.Invoke(ctx, CRUDModule_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CRUDModuleServer is the server API for CRUDModule service.
// All implementations must embed UnimplementedCRUDModuleServer
// for forward compatibility.
type CRUDModuleServer interface {
	// Create a new entity in the external system.
	Create(context.Context, *CRUDCreateRequest) (*CRUDCreateResponse, error)
	// Read a single entity by ID.
	Read(context.Context, *CRUDReadRequest) (*CRUDReadResponse, error)
	// Update an existing entity (partial update via fields map).
	Update(context.Context, *CRUDUpdateRequest) (*CRUDUpdateResponse, error)
	// Delete (or archive) an entity by ID.
	Delete(context.Context, *CRUDDeleteRequest) (*CRUDDeleteResponse, error)
	// List entities with optional filtering.
	List(context.Context, *CRUDListRequest) (*CRUDListResponse, error)
	mustEmbedUnimplementedCRUDModuleServer()
}

// UnimplementedCRUDModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCRUDModuleServer struct{}

func (UnimplementedCRUDModuleServer) Create(context.Context, *CRUDCreateRequest) (*CRUDCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCRUDModuleServer) Read(context.Context, *CRUDReadRequest) (*CRUDReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedCRUDModuleServer) Update(context.Context, *CRUDUpdateRequest) (*CRUDUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCRUDModuleServer) Delete(context.Context, *CRUDDeleteRequest) (*CRUDDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCRUDModuleServer) List(context.Context, *CRUDListRequest) (*CRUDListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCRUDModuleServer) mustEmbedUnimplementedCRUDModuleServer() {}
func (UnimplementedCRUDModuleServer) testEmbeddedByValue()                    {}

// UnsafeCRUDModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CRUDModuleServer will
// result in compilation errors.
type UnsafeCRUDModuleServer interface {
	mustEmbedUnimplementedCRUDModuleServer()
}

func RegisterCRUDModuleServer(s grpc.ServiceRegistrar, srv CRUDModuleServer) {
	// If the following call panics, it indicates UnimplementedCRUDModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CRUDModule_ServiceDesc, srv)
}

func _CRUDModule_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CRUDCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDModuleServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRUDModule_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDModuleServer).Create(ctx, req.(*CRUDCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRUDModule_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CRUDReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDModuleServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRUDModule_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDModuleServer).Read(ctx, req.(*CRUDReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRUDModule_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CRUDUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDModuleServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRUDModule_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDModuleServer).Update(ctx, req.(*CRUDUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRUDModule_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CRUDDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDModuleServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRUDModule_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDModuleServer).Delete(ctx, req.(*CRUDDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRUDModule_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CRUDListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDModuleServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRUDModule_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDModuleServer).List(ctx, req.(*CRUDListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CRUDModule_ServiceDesc is the grpc.ServiceDesc for CRUDModule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CRUDModule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mdemg.module.v1.CRUDModule",
	HandlerType: (*CRUDModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CRUDModule_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _CRUDModule_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CRUDModule_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CRUDModule_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CRUDModule_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mdemg-module.proto",
}
