// UNTS - Universal Hash Test Specification (Hash Verification Module)
// Alias: Nash Verification module
// Phase 38: Hash verification for UPTS, UATS, UBTS, USTS, UOTS, UAMS, UDTS frameworks

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/unts.proto

package untspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Framework identifies which test framework tracks the file
type Framework int32

const (
	Framework_FRAMEWORK_UNSPECIFIED Framework = 0
	Framework_FRAMEWORK_MANIFEST    Framework = 1 // docs/specs/manifest.sha256
	Framework_FRAMEWORK_UDTS        Framework = 2 // UDTS proto_sha256 fields
	Framework_FRAMEWORK_UATS        Framework = 3 // UATS spec hashes (future)
	Framework_FRAMEWORK_UBTS        Framework = 4 // UBTS spec hashes (future)
	Framework_FRAMEWORK_USTS        Framework = 5 // USTS spec hashes (future)
	Framework_FRAMEWORK_UOTS        Framework = 6 // UOTS spec hashes (future)
	Framework_FRAMEWORK_UAMS        Framework = 7 // UAMS spec hashes (future)
	Framework_FRAMEWORK_UPTS        Framework = 8 // UPTS parser hashes (future)
)

// Enum value maps for Framework.
var (
	Framework_name = map[int32]string{
		0: "FRAMEWORK_UNSPECIFIED",
		1: "FRAMEWORK_MANIFEST",
		2: "FRAMEWORK_UDTS",
		3: "FRAMEWORK_UATS",
		4: "FRAMEWORK_UBTS",
		5: "FRAMEWORK_USTS",
		6: "FRAMEWORK_UOTS",
		7: "FRAMEWORK_UAMS",
		8: "FRAMEWORK_UPTS",
	}
	Framework_value = map[string]int32{
		"FRAMEWORK_UNSPECIFIED": 0,
		"FRAMEWORK_MANIFEST":    1,
		"FRAMEWORK_UDTS":        2,
		"FRAMEWORK_UATS":        3,
		"FRAMEWORK_UBTS":        4,
		"FRAMEWORK_USTS":        5,
		"FRAMEWORK_UOTS":        6,
		"FRAMEWORK_UAMS":        7,
		"FRAMEWORK_UPTS":        8,
	}
)

func (x Framework) Enum() *Framework {
	p := new(Framework)
	*p = x
	return p
}

func (x Framework) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Framework) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_unts_proto_enumTypes[0].Descriptor()
}

func (Framework) Type() protoreflect.EnumType {
	return &file_api_proto_unts_proto_enumTypes[0]
}

func (x Framework) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Framework.Descriptor instead.
func (Framework) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{0}
}

// FileStatus represents the verification status of a tracked file
type FileStatus int32

const (
	FileStatus_FILE_STATUS_UNSPECIFIED FileStatus = 0
	FileStatus_FILE_STATUS_VERIFIED    FileStatus = 1 // Hash matches expected
	FileStatus_FILE_STATUS_MISMATCH    FileStatus = 2 // Hash does not match expected
	FileStatus_FILE_STATUS_UNKNOWN     FileStatus = 3 // File not found or hash not computed
	FileStatus_FILE_STATUS_REVERTED    FileStatus = 4 // Hash was reverted to a previous value
)

// Enum value maps for FileStatus.
var (
	FileStatus_name = map[int32]string{
		0: "FILE_STATUS_UNSPECIFIED",
		1: "FILE_STATUS_VERIFIED",
		2: "FILE_STATUS_MISMATCH",
		3: "FILE_STATUS_UNKNOWN",
		4: "FILE_STATUS_REVERTED",
	}
	FileStatus_value = map[string]int32{
		"FILE_STATUS_UNSPECIFIED": 0,
		"FILE_STATUS_VERIFIED":    1,
		"FILE_STATUS_MISMATCH":    2,
		"FILE_STATUS_UNKNOWN":     3,
		"FILE_STATUS_REVERTED":    4,
	}
)

func (x FileStatus) Enum() *FileStatus {
	p := new(FileStatus)
	*p = x
	return p
}

func (x FileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_unts_proto_enumTypes[1].Descriptor()
}

func (FileStatus) Type() protoreflect.EnumType {
	return &file_api_proto_unts_proto_enumTypes[1]
}

func (x FileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileStatus.Descriptor instead.
func (FileStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{1}
}

// HashSource indicates how the hash was set
type HashSource int32

const (
	HashSource_HASH_SOURCE_UNSPECIFIED HashSource = 0
	HashSource_HASH_SOURCE_MANIFEST    HashSource = 1 // From manifest.sha256
	HashSource_HASH_SOURCE_SPEC        HashSource = 2 // From UDTS/UATS spec file
	HashSource_HASH_SOURCE_REVERT      HashSource = 3 // From revert operation
	HashSource_HASH_SOURCE_MANUAL      HashSource = 4 // Manually set via API
	HashSource_HASH_SOURCE_CI          HashSource = 5 // Set by CI pipeline
)

// Enum value maps for HashSource.
var (
	HashSource_name = map[int32]string{
		0: "HASH_SOURCE_UNSPECIFIED",
		1: "HASH_SOURCE_MANIFEST",
		2: "HASH_SOURCE_SPEC",
		3: "HASH_SOURCE_REVERT",
		4: "HASH_SOURCE_MANUAL",
		5: "HASH_SOURCE_CI",
	}
	HashSource_value = map[string]int32{
		"HASH_SOURCE_UNSPECIFIED": 0,
		"HASH_SOURCE_MANIFEST":    1,
		"HASH_SOURCE_SPEC":        2,
		"HASH_SOURCE_REVERT":      3,
		"HASH_SOURCE_MANUAL":      4,
		"HASH_SOURCE_CI":          5,
	}
)

func (x HashSource) Enum() *HashSource {
	p := new(HashSource)
	*p = x
	return p
}

func (x HashSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashSource) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_unts_proto_enumTypes[2].Descriptor()
}

func (HashSource) Type() protoreflect.EnumType {
	return &file_api_proto_unts_proto_enumTypes[2]
}

func (x HashSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashSource.Descriptor instead.
func (HashSource) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{2}
}

// HashHistoryEntry represents a historical hash value
type HashHistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`                                    // SHA-256 hex (64 chars)
	UpdatedAt     string                 `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`         // ISO8601 timestamp
	Source        HashSource             `protobuf:"varint,3,opt,name=source,proto3,enum=mdemg.unts.v1.HashSource" json:"source,omitempty"` // How this hash was set
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashHistoryEntry) Reset() {
	*x = HashHistoryEntry{}
	mi := &file_api_proto_unts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashHistoryEntry) ProtoMessage() {}

func (x *HashHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashHistoryEntry.ProtoReflect.Descriptor instead.
func (*HashHistoryEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{0}
}

func (x *HashHistoryEntry) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *HashHistoryEntry) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *HashHistoryEntry) GetSource() HashSource {
	if x != nil {
		return x.Source
	}
	return HashSource_HASH_SOURCE_UNSPECIFIED
}

// VerifiedFileRecord represents a tracked file's verification state
type VerifiedFileRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                         // Repository-relative path
	Framework     Framework              `protobuf:"varint,2,opt,name=framework,proto3,enum=mdemg.unts.v1.Framework" json:"framework,omitempty"` // Which framework tracks this file
	CurrentHash   string                 `protobuf:"bytes,3,opt,name=current_hash,json=currentHash,proto3" json:"current_hash,omitempty"`        // Current expected SHA-256 hash
	Status        FileStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=mdemg.unts.v1.FileStatus" json:"status,omitempty"`      // Current verification status
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`              // Last status/hash update (ISO8601)
	History       []*HashHistoryEntry    `protobuf:"bytes,6,rep,name=history,proto3" json:"history,omitempty"`                                   // Last 3 hash values (newest first)
	SourceRef     string                 `protobuf:"bytes,7,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`              // Where hash is enforced (manifest line, spec filename)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifiedFileRecord) Reset() {
	*x = VerifiedFileRecord{}
	mi := &file_api_proto_unts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifiedFileRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifiedFileRecord) ProtoMessage() {}

func (x *VerifiedFileRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifiedFileRecord.ProtoReflect.Descriptor instead.
func (*VerifiedFileRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{1}
}

func (x *VerifiedFileRecord) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *VerifiedFileRecord) GetFramework() Framework {
	if x != nil {
		return x.Framework
	}
	return Framework_FRAMEWORK_UNSPECIFIED
}

func (x *VerifiedFileRecord) GetCurrentHash() string {
	if x != nil {
		return x.CurrentHash
	}
	return ""
}

func (x *VerifiedFileRecord) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FILE_STATUS_UNSPECIFIED
}

func (x *VerifiedFileRecord) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *VerifiedFileRecord) GetHistory() []*HashHistoryEntry {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *VerifiedFileRecord) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

// ListVerifiedFilesRequest filters the list of tracked files
type ListVerifiedFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Framework     Framework              `protobuf:"varint,1,opt,name=framework,proto3,enum=mdemg.unts.v1.Framework" json:"framework,omitempty"` // Optional: filter by framework
	Status        FileStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=mdemg.unts.v1.FileStatus" json:"status,omitempty"`      // Optional: filter by status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVerifiedFilesRequest) Reset() {
	*x = ListVerifiedFilesRequest{}
	mi := &file_api_proto_unts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVerifiedFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerifiedFilesRequest) ProtoMessage() {}

func (x *ListVerifiedFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerifiedFilesRequest.ProtoReflect.Descriptor instead.
func (*ListVerifiedFilesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{2}
}

func (x *ListVerifiedFilesRequest) GetFramework() Framework {
	if x != nil {
		return x.Framework
	}
	return Framework_FRAMEWORK_UNSPECIFIED
}

func (x *ListVerifiedFilesRequest) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FILE_STATUS_UNSPECIFIED
}

// ListVerifiedFilesResponse contains all matching tracked files
type ListVerifiedFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*VerifiedFileRecord  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	VerifiedCount int32                  `protobuf:"varint,3,opt,name=verified_count,json=verifiedCount,proto3" json:"verified_count,omitempty"`
	MismatchCount int32                  `protobuf:"varint,4,opt,name=mismatch_count,json=mismatchCount,proto3" json:"mismatch_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVerifiedFilesResponse) Reset() {
	*x = ListVerifiedFilesResponse{}
	mi := &file_api_proto_unts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVerifiedFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerifiedFilesResponse) ProtoMessage() {}

func (x *ListVerifiedFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerifiedFilesResponse.ProtoReflect.Descriptor instead.
func (*ListVerifiedFilesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{3}
}

func (x *ListVerifiedFilesResponse) GetFiles() []*VerifiedFileRecord {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListVerifiedFilesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListVerifiedFilesResponse) GetVerifiedCount() int32 {
	if x != nil {
		return x.VerifiedCount
	}
	return 0
}

func (x *ListVerifiedFilesResponse) GetMismatchCount() int32 {
	if x != nil {
		return x.MismatchCount
	}
	return 0
}

// GetFileStatusRequest identifies a single file to check
type GetFileStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                         // Repository-relative path
	Framework     Framework              `protobuf:"varint,2,opt,name=framework,proto3,enum=mdemg.unts.v1.Framework" json:"framework,omitempty"` // Optional: narrow by framework
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileStatusRequest) Reset() {
	*x = GetFileStatusRequest{}
	mi := &file_api_proto_unts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileStatusRequest) ProtoMessage() {}

func (x *GetFileStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileStatusRequest.ProtoReflect.Descriptor instead.
func (*GetFileStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileStatusRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetFileStatusRequest) GetFramework() Framework {
	if x != nil {
		return x.Framework
	}
	return Framework_FRAMEWORK_UNSPECIFIED
}

// GetFileStatusResponse contains the file's current state
type GetFileStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *VerifiedFileRecord    `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	ActualHash    string                 `protobuf:"bytes,2,opt,name=actual_hash,json=actualHash,proto3" json:"actual_hash,omitempty"` // Current on-disk hash (if computed)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileStatusResponse) Reset() {
	*x = GetFileStatusResponse{}
	mi := &file_api_proto_unts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileStatusResponse) ProtoMessage() {}

func (x *GetFileStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileStatusResponse.ProtoReflect.Descriptor instead.
func (*GetFileStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileStatusResponse) GetRecord() *VerifiedFileRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *GetFileStatusResponse) GetActualHash() string {
	if x != nil {
		return x.ActualHash
	}
	return ""
}

// GetHashHistoryRequest identifies a file for history lookup
type GetHashHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // Repository-relative path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHashHistoryRequest) Reset() {
	*x = GetHashHistoryRequest{}
	mi := &file_api_proto_unts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHashHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashHistoryRequest) ProtoMessage() {}

func (x *GetHashHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHashHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{6}
}

func (x *GetHashHistoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// GetHashHistoryResponse contains current hash and history
type GetHashHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	CurrentHash   string                 `protobuf:"bytes,2,opt,name=current_hash,json=currentHash,proto3" json:"current_hash,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	History       []*HashHistoryEntry    `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"` // Last 3 hashes (newest first)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHashHistoryResponse) Reset() {
	*x = GetHashHistoryResponse{}
	mi := &file_api_proto_unts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHashHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashHistoryResponse) ProtoMessage() {}

func (x *GetHashHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHashHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{7}
}

func (x *GetHashHistoryResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetHashHistoryResponse) GetCurrentHash() string {
	if x != nil {
		return x.CurrentHash
	}
	return ""
}

func (x *GetHashHistoryResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetHashHistoryResponse) GetHistory() []*HashHistoryEntry {
	if x != nil {
		return x.History
	}
	return nil
}

// RevertToPreviousHashRequest specifies which previous hash to restore
type RevertToPreviousHashRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*RevertToPreviousHashRequest_TargetHash
	//	*RevertToPreviousHashRequest_HistoryIndex
	Target        isRevertToPreviousHashRequest_Target `protobuf_oneof:"target"`
	RevertedBy    string                               `protobuf:"bytes,4,opt,name=reverted_by,json=revertedBy,proto3" json:"reverted_by,omitempty"` // Audit: who initiated the revert
	Reason        string                               `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                           // Audit: why reverting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevertToPreviousHashRequest) Reset() {
	*x = RevertToPreviousHashRequest{}
	mi := &file_api_proto_unts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertToPreviousHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertToPreviousHashRequest) ProtoMessage() {}

func (x *RevertToPreviousHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertToPreviousHashRequest.ProtoReflect.Descriptor instead.
func (*RevertToPreviousHashRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{8}
}

func (x *RevertToPreviousHashRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RevertToPreviousHashRequest) GetTarget() isRevertToPreviousHashRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *RevertToPreviousHashRequest) GetTargetHash() string {
	if x != nil {
		if x, ok := x.Target.(*RevertToPreviousHashRequest_TargetHash); ok {
			return x.TargetHash
		}
	}
	return ""
}

func (x *RevertToPreviousHashRequest) GetHistoryIndex() int32 {
	if x != nil {
		if x, ok := x.Target.(*RevertToPreviousHashRequest_HistoryIndex); ok {
			return x.HistoryIndex
		}
	}
	return 0
}

func (x *RevertToPreviousHashRequest) GetRevertedBy() string {
	if x != nil {
		return x.RevertedBy
	}
	return ""
}

func (x *RevertToPreviousHashRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type isRevertToPreviousHashRequest_Target interface {
	isRevertToPreviousHashRequest_Target()
}

type RevertToPreviousHashRequest_TargetHash struct {
	TargetHash string `protobuf:"bytes,2,opt,name=target_hash,json=targetHash,proto3,oneof"` // Revert to specific hash
}

type RevertToPreviousHashRequest_HistoryIndex struct {
	HistoryIndex int32 `protobuf:"varint,3,opt,name=history_index,json=historyIndex,proto3,oneof"` // Revert to history index (0 = most recent previous)
}

func (*RevertToPreviousHashRequest_TargetHash) isRevertToPreviousHashRequest_Target() {}

func (*RevertToPreviousHashRequest_HistoryIndex) isRevertToPreviousHashRequest_Target() {}

// RevertToPreviousHashResponse confirms the revert operation
type RevertToPreviousHashResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ok             bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	NewCurrentHash string                 `protobuf:"bytes,2,opt,name=new_current_hash,json=newCurrentHash,proto3" json:"new_current_hash,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // Error message if ok=false
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RevertToPreviousHashResponse) Reset() {
	*x = RevertToPreviousHashResponse{}
	mi := &file_api_proto_unts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertToPreviousHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertToPreviousHashResponse) ProtoMessage() {}

func (x *RevertToPreviousHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertToPreviousHashResponse.ProtoReflect.Descriptor instead.
func (*RevertToPreviousHashResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{9}
}

func (x *RevertToPreviousHashResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RevertToPreviousHashResponse) GetNewCurrentHash() string {
	if x != nil {
		return x.NewCurrentHash
	}
	return ""
}

func (x *RevertToPreviousHashResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RevertToPreviousHashResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// UpdateHashRequest manually sets a new expected hash
type UpdateHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	NewHash       string                 `protobuf:"bytes,2,opt,name=new_hash,json=newHash,proto3" json:"new_hash,omitempty"`               // SHA-256 hex (64 chars)
	Source        HashSource             `protobuf:"varint,3,opt,name=source,proto3,enum=mdemg.unts.v1.HashSource" json:"source,omitempty"` // How this hash was determined
	SourceRef     string                 `protobuf:"bytes,4,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`         // Reference (spec file, CI job, etc.)
	UpdatedBy     string                 `protobuf:"bytes,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`         // Audit: who updated
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`                                // Audit: why updating
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHashRequest) Reset() {
	*x = UpdateHashRequest{}
	mi := &file_api_proto_unts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHashRequest) ProtoMessage() {}

func (x *UpdateHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHashRequest.ProtoReflect.Descriptor instead.
func (*UpdateHashRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateHashRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdateHashRequest) GetNewHash() string {
	if x != nil {
		return x.NewHash
	}
	return ""
}

func (x *UpdateHashRequest) GetSource() HashSource {
	if x != nil {
		return x.Source
	}
	return HashSource_HASH_SOURCE_UNSPECIFIED
}

func (x *UpdateHashRequest) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *UpdateHashRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *UpdateHashRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// UpdateHashResponse confirms the update
type UpdateHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHashResponse) Reset() {
	*x = UpdateHashResponse{}
	mi := &file_api_proto_unts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHashResponse) ProtoMessage() {}

func (x *UpdateHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHashResponse.ProtoReflect.Descriptor instead.
func (*UpdateHashResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateHashResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UpdateHashResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UpdateHashResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// VerifyNowRequest triggers hash verification
type VerifyNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                         // Optional: specific file (empty = all)
	Framework     Framework              `protobuf:"varint,2,opt,name=framework,proto3,enum=mdemg.unts.v1.Framework" json:"framework,omitempty"` // Optional: filter by framework
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyNowRequest) Reset() {
	*x = VerifyNowRequest{}
	mi := &file_api_proto_unts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNowRequest) ProtoMessage() {}

func (x *VerifyNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNowRequest.ProtoReflect.Descriptor instead.
func (*VerifyNowRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyNowRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *VerifyNowRequest) GetFramework() Framework {
	if x != nil {
		return x.Framework
	}
	return Framework_FRAMEWORK_UNSPECIFIED
}

// FileVerifyResult contains the result for one file
type FileVerifyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Status        FileStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=mdemg.unts.v1.FileStatus" json:"status,omitempty"`
	ExpectedHash  string                 `protobuf:"bytes,3,opt,name=expected_hash,json=expectedHash,proto3" json:"expected_hash,omitempty"`
	ActualHash    string                 `protobuf:"bytes,4,opt,name=actual_hash,json=actualHash,proto3" json:"actual_hash,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"` // Error message if verification failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileVerifyResult) Reset() {
	*x = FileVerifyResult{}
	mi := &file_api_proto_unts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileVerifyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileVerifyResult) ProtoMessage() {}

func (x *FileVerifyResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileVerifyResult.ProtoReflect.Descriptor instead.
func (*FileVerifyResult) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{13}
}

func (x *FileVerifyResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileVerifyResult) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FILE_STATUS_UNSPECIFIED
}

func (x *FileVerifyResult) GetExpectedHash() string {
	if x != nil {
		return x.ExpectedHash
	}
	return ""
}

func (x *FileVerifyResult) GetActualHash() string {
	if x != nil {
		return x.ActualHash
	}
	return ""
}

func (x *FileVerifyResult) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *FileVerifyResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// VerifyNowResponse contains all verification results
type VerifyNowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*FileVerifyResult    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	VerifiedCount int32                  `protobuf:"varint,2,opt,name=verified_count,json=verifiedCount,proto3" json:"verified_count,omitempty"`
	MismatchCount int32                  `protobuf:"varint,3,opt,name=mismatch_count,json=mismatchCount,proto3" json:"mismatch_count,omitempty"`
	ErrorCount    int32                  `protobuf:"varint,4,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyNowResponse) Reset() {
	*x = VerifyNowResponse{}
	mi := &file_api_proto_unts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNowResponse) ProtoMessage() {}

func (x *VerifyNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNowResponse.ProtoReflect.Descriptor instead.
func (*VerifyNowResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyNowResponse) GetResults() []*FileVerifyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *VerifyNowResponse) GetVerifiedCount() int32 {
	if x != nil {
		return x.VerifiedCount
	}
	return 0
}

func (x *VerifyNowResponse) GetMismatchCount() int32 {
	if x != nil {
		return x.MismatchCount
	}
	return 0
}

func (x *VerifyNowResponse) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

// RegisterTrackedFileRequest adds a new file to the registry
type RegisterTrackedFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                         // Repository-relative path
	Framework     Framework              `protobuf:"varint,2,opt,name=framework,proto3,enum=mdemg.unts.v1.Framework" json:"framework,omitempty"` // Which framework tracks this file
	InitialHash   string                 `protobuf:"bytes,3,opt,name=initial_hash,json=initialHash,proto3" json:"initial_hash,omitempty"`        // Initial expected SHA-256 hash
	SourceRef     string                 `protobuf:"bytes,4,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`              // Where hash is enforced
	RegisteredBy  string                 `protobuf:"bytes,5,opt,name=registered_by,json=registeredBy,proto3" json:"registered_by,omitempty"`     // Audit: who registered
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTrackedFileRequest) Reset() {
	*x = RegisterTrackedFileRequest{}
	mi := &file_api_proto_unts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTrackedFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTrackedFileRequest) ProtoMessage() {}

func (x *RegisterTrackedFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTrackedFileRequest.ProtoReflect.Descriptor instead.
func (*RegisterTrackedFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterTrackedFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RegisterTrackedFileRequest) GetFramework() Framework {
	if x != nil {
		return x.Framework
	}
	return Framework_FRAMEWORK_UNSPECIFIED
}

func (x *RegisterTrackedFileRequest) GetInitialHash() string {
	if x != nil {
		return x.InitialHash
	}
	return ""
}

func (x *RegisterTrackedFileRequest) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *RegisterTrackedFileRequest) GetRegisteredBy() string {
	if x != nil {
		return x.RegisteredBy
	}
	return ""
}

// RegisterTrackedFileResponse confirms registration
type RegisterTrackedFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTrackedFileResponse) Reset() {
	*x = RegisterTrackedFileResponse{}
	mi := &file_api_proto_unts_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTrackedFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTrackedFileResponse) ProtoMessage() {}

func (x *RegisterTrackedFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_unts_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTrackedFileResponse.ProtoReflect.Descriptor instead.
func (*RegisterTrackedFileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_unts_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterTrackedFileResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterTrackedFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_unts_proto protoreflect.FileDescriptor

const file_api_proto_unts_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/unts.proto\x12\rmdemg.unts.v1\"x\n" +
	"\x10HashHistoryEntry\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\tR\tupdatedAt\x121\n" +
	"\x06source\x18\x03 \x01(\x0e2\x19.mdemg.unts.v1.HashSourceR\x06source\"\xaf\x02\n" +
	"\x12VerifiedFileRecord\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x126\n" +
	"\tframework\x18\x02 \x01(\x0e2\x18.mdemg.unts.v1.FrameworkR\tframework\x12!\n" +
	"\fcurrent_hash\x18\x03 \x01(\tR\vcurrentHash\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.mdemg.unts.v1.FileStatusR\x06status\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x129\n" +
	"\ahistory\x18\x06 \x03(\v2\x1f.mdemg.unts.v1.HashHistoryEntryR\ahistory\x12\x1d\n" +
	"\n" +
	"source_ref\x18\a \x01(\tR\tsourceRef\"\x85\x01\n" +
	"\x18ListVerifiedFilesRequest\x126\n" +
	"\tframework\x18\x01 \x01(\x0e2\x18.mdemg.unts.v1.FrameworkR\tframework\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.mdemg.unts.v1.FileStatusR\x06status\"\xc3\x01\n" +
	"\x19ListVerifiedFilesResponse\x127\n" +
	"\x05files\x18\x01 \x03(\v2!.mdemg.unts.v1.VerifiedFileRecordR\x05files\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12%\n" +
	"\x0everified_count\x18\x03 \x01(\x05R\rverifiedCount\x12%\n" +
	"\x0emismatch_count\x18\x04 \x01(\x05R\rmismatchCount\"b\n" +
	"\x14GetFileStatusRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x126\n" +
	"\tframework\x18\x02 \x01(\x0e2\x18.mdemg.unts.v1.FrameworkR\tframework\"s\n" +
	"\x15GetFileStatusResponse\x129\n" +
	"\x06record\x18\x01 \x01(\v2!.mdemg.unts.v1.VerifiedFileRecordR\x06record\x12\x1f\n" +
	"\vactual_hash\x18\x02 \x01(\tR\n" +
	"actualHash\"+\n" +
	"\x15GetHashHistoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xa9\x01\n" +
	"\x16GetHashHistoryResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\fcurrent_hash\x18\x02 \x01(\tR\vcurrentHash\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x129\n" +
	"\ahistory\x18\x04 \x03(\v2\x1f.mdemg.unts.v1.HashHistoryEntryR\ahistory\"\xbe\x01\n" +
	"\x1bRevertToPreviousHashRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\vtarget_hash\x18\x02 \x01(\tH\x00R\n" +
	"targetHash\x12%\n" +
	"\rhistory_index\x18\x03 \x01(\x05H\x00R\fhistoryIndex\x12\x1f\n" +
	"\vreverted_by\x18\x04 \x01(\tR\n" +
	"revertedBy\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reasonB\b\n" +
	"\x06target\"\x8d\x01\n" +
	"\x1cRevertToPreviousHashResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12(\n" +
	"\x10new_current_hash\x18\x02 \x01(\tR\x0enewCurrentHash\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xcb\x01\n" +
	"\x11UpdateHashRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bnew_hash\x18\x02 \x01(\tR\anewHash\x121\n" +
	"\x06source\x18\x03 \x01(\x0e2\x19.mdemg.unts.v1.HashSourceR\x06source\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x04 \x01(\tR\tsourceRef\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x05 \x01(\tR\tupdatedBy\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"Y\n" +
	"\x12UpdateHashResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\tR\tupdatedAt\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"^\n" +
	"\x10VerifyNowRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x126\n" +
	"\tframework\x18\x02 \x01(\x0e2\x18.mdemg.unts.v1.FrameworkR\tframework\"\xd4\x01\n" +
	"\x10FileVerifyResult\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.mdemg.unts.v1.FileStatusR\x06status\x12#\n" +
	"\rexpected_hash\x18\x03 \x01(\tR\fexpectedHash\x12\x1f\n" +
	"\vactual_hash\x18\x04 \x01(\tR\n" +
	"actualHash\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xbd\x01\n" +
	"\x11VerifyNowResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.mdemg.unts.v1.FileVerifyResultR\aresults\x12%\n" +
	"\x0everified_count\x18\x02 \x01(\x05R\rverifiedCount\x12%\n" +
	"\x0emismatch_count\x18\x03 \x01(\x05R\rmismatchCount\x12\x1f\n" +
	"\verror_count\x18\x04 \x01(\x05R\n" +
	"errorCount\"\xcf\x01\n" +
	"\x1aRegisterTrackedFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x126\n" +
	"\tframework\x18\x02 \x01(\x0e2\x18.mdemg.unts.v1.FrameworkR\tframework\x12!\n" +
	"\finitial_hash\x18\x03 \x01(\tR\vinitialHash\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x04 \x01(\tR\tsourceRef\x12#\n" +
	"\rregistered_by\x18\x05 \x01(\tR\fregisteredBy\"C\n" +
	"\x1bRegisterTrackedFileResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*\xca\x01\n" +
	"\tFramework\x12\x19\n" +
	"\x15FRAMEWORK_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FRAMEWORK_MANIFEST\x10\x01\x12\x12\n" +
	"\x0eFRAMEWORK_UDTS\x10\x02\x12\x12\n" +
	"\x0eFRAMEWORK_UATS\x10\x03\x12\x12\n" +
	"\x0eFRAMEWORK_UBTS\x10\x04\x12\x12\n" +
	"\x0eFRAMEWORK_USTS\x10\x05\x12\x12\n" +
	"\x0eFRAMEWORK_UOTS\x10\x06\x12\x12\n" +
	"\x0eFRAMEWORK_UAMS\x10\a\x12\x12\n" +
	"\x0eFRAMEWORK_UPTS\x10\b*\x90\x01\n" +
	"\n" +
	"FileStatus\x12\x1b\n" +
	"\x17FILE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14FILE_STATUS_VERIFIED\x10\x01\x12\x18\n" +
	"\x14FILE_STATUS_MISMATCH\x10\x02\x12\x17\n" +
	"\x13FILE_STATUS_UNKNOWN\x10\x03\x12\x18\n" +
	"\x14FILE_STATUS_REVERTED\x10\x04*\x9d\x01\n" +
	"\n" +
	"HashSource\x12\x1b\n" +
	"\x17HASH_SOURCE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14HASH_SOURCE_MANIFEST\x10\x01\x12\x14\n" +
	"\x10HASH_SOURCE_SPEC\x10\x02\x12\x16\n" +
	"\x12HASH_SOURCE_REVERT\x10\x03\x12\x16\n" +
	"\x12HASH_SOURCE_MANUAL\x10\x04\x12\x12\n" +
	"\x0eHASH_SOURCE_CI\x10\x052\xb7\x05\n" +
	"\x10HashVerification\x12f\n" +
	"\x11ListVerifiedFiles\x12'.mdemg.unts.v1.ListVerifiedFilesRequest\x1a(.mdemg.unts.v1.ListVerifiedFilesResponse\x12Z\n" +
	"\rGetFileStatus\x12#.mdemg.unts.v1.GetFileStatusRequest\x1a$.mdemg.unts.v1.GetFileStatusResponse\x12]\n" +
	"\x0eGetHashHistory\x12$.mdemg.unts.v1.GetHashHistoryRequest\x1a%.mdemg.unts.v1.GetHashHistoryResponse\x12o\n" +
	"\x14RevertToPreviousHash\x12*.mdemg.unts.v1.RevertToPreviousHashRequest\x1a+.mdemg.unts.v1.RevertToPreviousHashResponse\x12Q\n" +
	"\n" +
	"UpdateHash\x12 .mdemg.unts.v1.UpdateHashRequest\x1a!.mdemg.unts.v1.UpdateHashResponse\x12N\n" +
	"\tVerifyNow\x12\x1f.mdemg.unts.v1.VerifyNowRequest\x1a .mdemg.unts.v1.VerifyNowResponse\x12l\n" +
	"\x13RegisterTrackedFile\x12).mdemg.unts.v1.RegisterTrackedFileRequest\x1a*.mdemg.unts.v1.RegisterTrackedFileResponseB\x12Z\x10mdemg/api/untspbb\x06proto3"

var (
	file_api_proto_unts_proto_rawDescOnce sync.Once
	file_api_proto_unts_proto_rawDescData []byte
)

func file_api_proto_unts_proto_rawDescGZIP() []byte {
	file_api_proto_unts_proto_rawDescOnce.Do(func() {
		file_api_proto_unts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_unts_proto_rawDesc), len(file_api_proto_unts_proto_rawDesc)))
	})
	return file_api_proto_unts_proto_rawDescData
}

var file_api_proto_unts_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_unts_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_proto_unts_proto_goTypes = []any{
	(Framework)(0),                       // 0: mdemg.unts.v1.Framework
	(FileStatus)(0),                      // 1: mdemg.unts.v1.FileStatus
	(HashSource)(0),                      // 2: mdemg.unts.v1.HashSource
	(*HashHistoryEntry)(nil),             // 3: mdemg.unts.v1.HashHistoryEntry
	(*VerifiedFileRecord)(nil),           // 4: mdemg.unts.v1.VerifiedFileRecord
	(*ListVerifiedFilesRequest)(nil),     // 5: mdemg.unts.v1.ListVerifiedFilesRequest
	(*ListVerifiedFilesResponse)(nil),    // 6: mdemg.unts.v1.ListVerifiedFilesResponse
	(*GetFileStatusRequest)(nil),         // 7: mdemg.unts.v1.GetFileStatusRequest
	(*GetFileStatusResponse)(nil),        // 8: mdemg.unts.v1.GetFileStatusResponse
	(*GetHashHistoryRequest)(nil),        // 9: mdemg.unts.v1.GetHashHistoryRequest
	(*GetHashHistoryResponse)(nil),       // 10: mdemg.unts.v1.GetHashHistoryResponse
	(*RevertToPreviousHashRequest)(nil),  // 11: mdemg.unts.v1.RevertToPreviousHashRequest
	(*RevertToPreviousHashResponse)(nil), // 12: mdemg.unts.v1.RevertToPreviousHashResponse
	(*UpdateHashRequest)(nil),            // 13: mdemg.unts.v1.UpdateHashRequest
	(*UpdateHashResponse)(nil),           // 14: mdemg.unts.v1.UpdateHashResponse
	(*VerifyNowRequest)(nil),             // 15: mdemg.unts.v1.VerifyNowRequest
	(*FileVerifyResult)(nil),             // 16: mdemg.unts.v1.FileVerifyResult
	(*VerifyNowResponse)(nil),            // 17: mdemg.unts.v1.VerifyNowResponse
	(*RegisterTrackedFileRequest)(nil),   // 18: mdemg.unts.v1.RegisterTrackedFileRequest
	(*RegisterTrackedFileResponse)(nil),  // 19: mdemg.unts.v1.RegisterTrackedFileResponse
}
var file_api_proto_unts_proto_depIdxs = []int32{
	2,  // 0: mdemg.unts.v1.HashHistoryEntry.source:type_name -> mdemg.unts.v1.HashSource
	0,  // 1: mdemg.unts.v1.VerifiedFileRecord.framework:type_name -> mdemg.unts.v1.Framework
	1,  // 2: mdemg.unts.v1.VerifiedFileRecord.status:type_name -> mdemg.unts.v1.FileStatus
	3,  // 3: mdemg.unts.v1.VerifiedFileRecord.history:type_name -> mdemg.unts.v1.HashHistoryEntry
	0,  // 4: mdemg.unts.v1.ListVerifiedFilesRequest.framework:type_name -> mdemg.unts.v1.Framework
	1,  // 5: mdemg.unts.v1.ListVerifiedFilesRequest.status:type_name -> mdemg.unts.v1.FileStatus
	4,  // 6: mdemg.unts.v1.ListVerifiedFilesResponse.files:type_name -> mdemg.unts.v1.VerifiedFileRecord
	0,  // 7: mdemg.unts.v1.GetFileStatusRequest.framework:type_name -> mdemg.unts.v1.Framework
	4,  // 8: mdemg.unts.v1.GetFileStatusResponse.record:type_name -> mdemg.unts.v1.VerifiedFileRecord
	3,  // 9: mdemg.unts.v1.GetHashHistoryResponse.history:type_name -> mdemg.unts.v1.HashHistoryEntry
	2,  // 10: mdemg.unts.v1.UpdateHashRequest.source:type_name -> mdemg.unts.v1.HashSource
	0,  // 11: mdemg.unts.v1.VerifyNowRequest.framework:type_name -> mdemg.unts.v1.Framework
	1,  // 12: mdemg.unts.v1.FileVerifyResult.status:type_name -> mdemg.unts.v1.FileStatus
	16, // 13: mdemg.unts.v1.VerifyNowResponse.results:type_name -> mdemg.unts.v1.FileVerifyResult
	0,  // 14: mdemg.unts.v1.RegisterTrackedFileRequest.framework:type_name -> mdemg.unts.v1.Framework
	5,  // 15: mdemg.unts.v1.HashVerification.ListVerifiedFiles:input_type -> mdemg.unts.v1.ListVerifiedFilesRequest
	7,  // 16: mdemg.unts.v1.HashVerification.GetFileStatus:input_type -> mdemg.unts.v1.GetFileStatusRequest
	9,  // 17: mdemg.unts.v1.HashVerification.GetHashHistory:input_type -> mdemg.unts.v1.GetHashHistoryRequest
	11, // 18: mdemg.unts.v1.HashVerification.RevertToPreviousHash:input_type -> mdemg.unts.v1.RevertToPreviousHashRequest
	13, // 19: mdemg.unts.v1.HashVerification.UpdateHash:input_type -> mdemg.unts.v1.UpdateHashRequest
	15, // 20: mdemg.unts.v1.HashVerification.VerifyNow:input_type -> mdemg.unts.v1.VerifyNowRequest
	18, // 21: mdemg.unts.v1.HashVerification.RegisterTrackedFile:input_type -> mdemg.unts.v1.RegisterTrackedFileRequest
	6,  // 22: mdemg.unts.v1.HashVerification.ListVerifiedFiles:output_type -> mdemg.unts.v1.ListVerifiedFilesResponse
	8,  // 23: mdemg.unts.v1.HashVerification.GetFileStatus:output_type -> mdemg.unts.v1.GetFileStatusResponse
	10, // 24: mdemg.unts.v1.HashVerification.GetHashHistory:output_type -> mdemg.unts.v1.GetHashHistoryResponse
	12, // 25: mdemg.unts.v1.HashVerification.RevertToPreviousHash:output_type -> mdemg.unts.v1.RevertToPreviousHashResponse
	14, // 26: mdemg.unts.v1.HashVerification.UpdateHash:output_type -> mdemg.unts.v1.UpdateHashResponse
	17, // 27: mdemg.unts.v1.HashVerification.VerifyNow:output_type -> mdemg.unts.v1.VerifyNowResponse
	19, // 28: mdemg.unts.v1.HashVerification.RegisterTrackedFile:output_type -> mdemg.unts.v1.RegisterTrackedFileResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_proto_unts_proto_init() }
func file_api_proto_unts_proto_init() {
	if File_api_proto_unts_proto != nil {
		return
	}
	file_api_proto_unts_proto_msgTypes[8].OneofWrappers = []any{
		(*RevertToPreviousHashRequest_TargetHash)(nil),
		(*RevertToPreviousHashRequest_HistoryIndex)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_unts_proto_rawDesc), len(file_api_proto_unts_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_unts_proto_goTypes,
		DependencyIndexes: file_api_proto_unts_proto_depIdxs,
		EnumInfos:         file_api_proto_unts_proto_enumTypes,
		MessageInfos:      file_api_proto_unts_proto_msgTypes,
	}.Build()
	File_api_proto_unts_proto = out.File
	file_api_proto_unts_proto_goTypes = nil
	file_api_proto_unts_proto_depIdxs = nil
}
