// UNTS - Universal Hash Test Specification (Hash Verification Module)
// Alias: Nash Verification module
// Phase 38: Hash verification for UPTS, UATS, UBTS, USTS, UOTS, UAMS, UDTS frameworks

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/proto/unts.proto

package untspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HashVerification_ListVerifiedFiles_FullMethodName    = "/mdemg.unts.v1.HashVerification/ListVerifiedFiles"
	HashVerification_GetFileStatus_FullMethodName        = "/mdemg.unts.v1.HashVerification/GetFileStatus"
	HashVerification_GetHashHistory_FullMethodName       = "/mdemg.unts.v1.HashVerification/GetHashHistory"
	HashVerification_RevertToPreviousHash_FullMethodName = "/mdemg.unts.v1.HashVerification/RevertToPreviousHash"
	HashVerification_UpdateHash_FullMethodName           = "/mdemg.unts.v1.HashVerification/UpdateHash"
	HashVerification_VerifyNow_FullMethodName            = "/mdemg.unts.v1.HashVerification/VerifyNow"
	HashVerification_RegisterTrackedFile_FullMethodName  = "/mdemg.unts.v1.HashVerification/RegisterTrackedFile"
)

// HashVerificationClient is the client API for HashVerification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HashVerification provides hash verification operations for tracked files
// across MDEMG frameworks (manifest, UDTS, UATS, etc.)
type HashVerificationClient interface {
	// ListVerifiedFiles returns all tracked files with their current hash and status
	ListVerifiedFiles(ctx context.Context, in *ListVerifiedFilesRequest, opts ...grpc.CallOption) (*ListVerifiedFilesResponse, error)
	// GetFileStatus returns the status of a single tracked file
	GetFileStatus(ctx context.Context, in *GetFileStatusRequest, opts ...grpc.CallOption) (*GetFileStatusResponse, error)
	// GetHashHistory returns the current hash and last 3 historical hashes
	GetHashHistory(ctx context.Context, in *GetHashHistoryRequest, opts ...grpc.CallOption) (*GetHashHistoryResponse, error)
	// RevertToPreviousHash sets the expected hash back to a previous value
	RevertToPreviousHash(ctx context.Context, in *RevertToPreviousHashRequest, opts ...grpc.CallOption) (*RevertToPreviousHashResponse, error)
	// UpdateHash manually updates the expected hash for a file
	UpdateHash(ctx context.Context, in *UpdateHashRequest, opts ...grpc.CallOption) (*UpdateHashResponse, error)
	// VerifyNow recomputes file hashes and compares to expected values
	VerifyNow(ctx context.Context, in *VerifyNowRequest, opts ...grpc.CallOption) (*VerifyNowResponse, error)
	// RegisterTrackedFile adds a new file to the registry
	RegisterTrackedFile(ctx context.Context, in *RegisterTrackedFileRequest, opts ...grpc.CallOption) (*RegisterTrackedFileResponse, error)
}

type hashVerificationClient struct {
	cc grpc.ClientConnInterface
}

func NewHashVerificationClient(cc grpc.ClientConnInterface) HashVerificationClient {
	return &hashVerificationClient{cc}
}

func (c *hashVerificationClient) ListVerifiedFiles(ctx context.Context, in *ListVerifiedFilesRequest, opts ...grpc.CallOption) (*ListVerifiedFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVerifiedFilesResponse)
	err := c.cc.Invoke(ctx, HashVerification_ListVerifiedFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashVerificationClient) GetFileStatus(ctx context.Context, in *GetFileStatusRequest, opts ...grpc.CallOption) (*GetFileStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileStatusResponse)
	err := c.cc.Invoke(ctx, HashVerification_GetFileStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashVerificationClient) GetHashHistory(ctx context.Context, in *GetHashHistoryRequest, opts ...grpc.CallOption) (*GetHashHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHashHistoryResponse)
	err := c.cc.Invoke(ctx, HashVerification_GetHashHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashVerificationClient) RevertToPreviousHash(ctx context.Context, in *RevertToPreviousHashRequest, opts ...grpc.CallOption) (*RevertToPreviousHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevertToPreviousHashResponse)
	err := c.cc.Invoke(ctx, HashVerification_RevertToPreviousHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashVerificationClient) UpdateHash(ctx context.Context, in *UpdateHashRequest, opts ...grpc.CallOption) (*UpdateHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHashResponse)
	err := c.cc.Invoke(ctx, HashVerification_UpdateHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashVerificationClient) VerifyNow(ctx context.Context, in *VerifyNowRequest, opts ...grpc.CallOption) (*VerifyNowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyNowResponse)
	err := c.cc.Invoke(ctx, HashVerification_VerifyNow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashVerificationClient) RegisterTrackedFile(ctx context.Context, in *RegisterTrackedFileRequest, opts ...grpc.CallOption) (*RegisterTrackedFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTrackedFileResponse)
	err := c.cc.Invoke(ctx, HashVerification_RegisterTrackedFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HashVerificationServer is the server API for HashVerification service.
// All implementations must embed UnimplementedHashVerificationServer
// for forward compatibility.
//
// HashVerification provides hash verification operations for tracked files
// across MDEMG frameworks (manifest, UDTS, UATS, etc.)
type HashVerificationServer interface {
	// ListVerifiedFiles returns all tracked files with their current hash and status
	ListVerifiedFiles(context.Context, *ListVerifiedFilesRequest) (*ListVerifiedFilesResponse, error)
	// GetFileStatus returns the status of a single tracked file
	GetFileStatus(context.Context, *GetFileStatusRequest) (*GetFileStatusResponse, error)
	// GetHashHistory returns the current hash and last 3 historical hashes
	GetHashHistory(context.Context, *GetHashHistoryRequest) (*GetHashHistoryResponse, error)
	// RevertToPreviousHash sets the expected hash back to a previous value
	RevertToPreviousHash(context.Context, *RevertToPreviousHashRequest) (*RevertToPreviousHashResponse, error)
	// UpdateHash manually updates the expected hash for a file
	UpdateHash(context.Context, *UpdateHashRequest) (*UpdateHashResponse, error)
	// VerifyNow recomputes file hashes and compares to expected values
	VerifyNow(context.Context, *VerifyNowRequest) (*VerifyNowResponse, error)
	// RegisterTrackedFile adds a new file to the registry
	RegisterTrackedFile(context.Context, *RegisterTrackedFileRequest) (*RegisterTrackedFileResponse, error)
	mustEmbedUnimplementedHashVerificationServer()
}

// UnimplementedHashVerificationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHashVerificationServer struct{}

func (UnimplementedHashVerificationServer) ListVerifiedFiles(context.Context, *ListVerifiedFilesRequest) (*ListVerifiedFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVerifiedFiles not implemented")
}
func (UnimplementedHashVerificationServer) GetFileStatus(context.Context, *GetFileStatusRequest) (*GetFileStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileStatus not implemented")
}
func (UnimplementedHashVerificationServer) GetHashHistory(context.Context, *GetHashHistoryRequest) (*GetHashHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHashHistory not implemented")
}
func (UnimplementedHashVerificationServer) RevertToPreviousHash(context.Context, *RevertToPreviousHashRequest) (*RevertToPreviousHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevertToPreviousHash not implemented")
}
func (UnimplementedHashVerificationServer) UpdateHash(context.Context, *UpdateHashRequest) (*UpdateHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateHash not implemented")
}
func (UnimplementedHashVerificationServer) VerifyNow(context.Context, *VerifyNowRequest) (*VerifyNowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyNow not implemented")
}
func (UnimplementedHashVerificationServer) RegisterTrackedFile(context.Context, *RegisterTrackedFileRequest) (*RegisterTrackedFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTrackedFile not implemented")
}
func (UnimplementedHashVerificationServer) mustEmbedUnimplementedHashVerificationServer() {}
func (UnimplementedHashVerificationServer) testEmbeddedByValue()                          {}

// UnsafeHashVerificationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HashVerificationServer will
// result in compilation errors.
type UnsafeHashVerificationServer interface {
	mustEmbedUnimplementedHashVerificationServer()
}

func RegisterHashVerificationServer(s grpc.ServiceRegistrar, srv HashVerificationServer) {
	// If the following call panics, it indicates UnimplementedHashVerificationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HashVerification_ServiceDesc, srv)
}

func _HashVerification_ListVerifiedFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVerifiedFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashVerificationServer).ListVerifiedFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashVerification_ListVerifiedFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashVerificationServer).ListVerifiedFiles(ctx, req.(*ListVerifiedFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashVerification_GetFileStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashVerificationServer).GetFileStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashVerification_GetFileStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashVerificationServer).GetFileStatus(ctx, req.(*GetFileStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashVerification_GetHashHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHashHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashVerificationServer).GetHashHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashVerification_GetHashHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashVerificationServer).GetHashHistory(ctx, req.(*GetHashHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashVerification_RevertToPreviousHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevertToPreviousHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashVerificationServer).RevertToPreviousHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashVerification_RevertToPreviousHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashVerificationServer).RevertToPreviousHash(ctx, req.(*RevertToPreviousHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashVerification_UpdateHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashVerificationServer).UpdateHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashVerification_UpdateHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashVerificationServer).UpdateHash(ctx, req.(*UpdateHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashVerification_VerifyNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyNowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashVerificationServer).VerifyNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashVerification_VerifyNow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashVerificationServer).VerifyNow(ctx, req.(*VerifyNowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashVerification_RegisterTrackedFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTrackedFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashVerificationServer).RegisterTrackedFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashVerification_RegisterTrackedFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashVerificationServer).RegisterTrackedFile(ctx, req.(*RegisterTrackedFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HashVerification_ServiceDesc is the grpc.ServiceDesc for HashVerification service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HashVerification_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mdemg.unts.v1.HashVerification",
	HandlerType: (*HashVerificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListVerifiedFiles",
			Handler:    _HashVerification_ListVerifiedFiles_Handler,
		},
		{
			MethodName: "GetFileStatus",
			Handler:    _HashVerification_GetFileStatus_Handler,
		},
		{
			MethodName: "GetHashHistory",
			Handler:    _HashVerification_GetHashHistory_Handler,
		},
		{
			MethodName: "RevertToPreviousHash",
			Handler:    _HashVerification_RevertToPreviousHash_Handler,
		},
		{
			MethodName: "UpdateHash",
			Handler:    _HashVerification_UpdateHash_Handler,
		},
		{
			MethodName: "VerifyNow",
			Handler:    _HashVerification_VerifyNow_Handler,
		},
		{
			MethodName: "RegisterTrackedFile",
			Handler:    _HashVerification_RegisterTrackedFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/unts.proto",
}
