// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/proto/devspace.proto

package devspacepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DevSpace_RegisterAgent_FullMethodName   = "/mdemg.devspace.v1.DevSpace/RegisterAgent"
	DevSpace_DeregisterAgent_FullMethodName = "/mdemg.devspace.v1.DevSpace/DeregisterAgent"
	DevSpace_ListExports_FullMethodName     = "/mdemg.devspace.v1.DevSpace/ListExports"
	DevSpace_PublishExport_FullMethodName   = "/mdemg.devspace.v1.DevSpace/PublishExport"
	DevSpace_PullExport_FullMethodName      = "/mdemg.devspace.v1.DevSpace/PullExport"
	DevSpace_Connect_FullMethodName         = "/mdemg.devspace.v1.DevSpace/Connect"
)

// DevSpaceClient is the client API for DevSpace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DevSpaceClient interface {
	// RegisterAgent registers an agent in a DevSpace (idempotent).
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	// DeregisterAgent removes an agent from a DevSpace.
	DeregisterAgent(ctx context.Context, in *DeregisterAgentRequest, opts ...grpc.CallOption) (*DeregisterAgentResponse, error)
	// ListExports returns the catalog of published exports for a DevSpace.
	ListExports(ctx context.Context, in *ListExportsRequest, opts ...grpc.CallOption) (*ListExportsResponse, error)
	// PublishExport uploads an export to the hub and adds it to the catalog.
	PublishExport(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PublishExportChunk, PublishExportResponse], error)
	// PullExport streams a published export by ID to the caller.
	PullExport(ctx context.Context, in *PullExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullExportChunk], error)
	// Connect (Phase 3) opens a bidirectional stream for inter-agent messaging.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, AgentMessage], error)
}

type devSpaceClient struct {
	cc grpc.ClientConnInterface
}

func NewDevSpaceClient(cc grpc.ClientConnInterface) DevSpaceClient {
	return &devSpaceClient{cc}
}

func (c *devSpaceClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, DevSpace_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devSpaceClient) DeregisterAgent(ctx context.Context, in *DeregisterAgentRequest, opts ...grpc.CallOption) (*DeregisterAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterAgentResponse)
	err := c.cc.Invoke(ctx, DevSpace_DeregisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devSpaceClient) ListExports(ctx context.Context, in *ListExportsRequest, opts ...grpc.CallOption) (*ListExportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExportsResponse)
	err := c.cc.Invoke(ctx, DevSpace_ListExports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devSpaceClient) PublishExport(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PublishExportChunk, PublishExportResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DevSpace_ServiceDesc.Streams[0], DevSpace_PublishExport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PublishExportChunk, PublishExportResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevSpace_PublishExportClient = grpc.ClientStreamingClient[PublishExportChunk, PublishExportResponse]

func (c *devSpaceClient) PullExport(ctx context.Context, in *PullExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullExportChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DevSpace_ServiceDesc.Streams[1], DevSpace_PullExport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullExportRequest, PullExportChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevSpace_PullExportClient = grpc.ServerStreamingClient[PullExportChunk]

func (c *devSpaceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, AgentMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DevSpace_ServiceDesc.Streams[2], DevSpace_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, AgentMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevSpace_ConnectClient = grpc.BidiStreamingClient[AgentMessage, AgentMessage]

// DevSpaceServer is the server API for DevSpace service.
// All implementations must embed UnimplementedDevSpaceServer
// for forward compatibility.
type DevSpaceServer interface {
	// RegisterAgent registers an agent in a DevSpace (idempotent).
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	// DeregisterAgent removes an agent from a DevSpace.
	DeregisterAgent(context.Context, *DeregisterAgentRequest) (*DeregisterAgentResponse, error)
	// ListExports returns the catalog of published exports for a DevSpace.
	ListExports(context.Context, *ListExportsRequest) (*ListExportsResponse, error)
	// PublishExport uploads an export to the hub and adds it to the catalog.
	PublishExport(grpc.ClientStreamingServer[PublishExportChunk, PublishExportResponse]) error
	// PullExport streams a published export by ID to the caller.
	PullExport(*PullExportRequest, grpc.ServerStreamingServer[PullExportChunk]) error
	// Connect (Phase 3) opens a bidirectional stream for inter-agent messaging.
	Connect(grpc.BidiStreamingServer[AgentMessage, AgentMessage]) error
	mustEmbedUnimplementedDevSpaceServer()
}

// UnimplementedDevSpaceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDevSpaceServer struct{}

func (UnimplementedDevSpaceServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedDevSpaceServer) DeregisterAgent(context.Context, *DeregisterAgentRequest) (*DeregisterAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterAgent not implemented")
}
func (UnimplementedDevSpaceServer) ListExports(context.Context, *ListExportsRequest) (*ListExportsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExports not implemented")
}
func (UnimplementedDevSpaceServer) PublishExport(grpc.ClientStreamingServer[PublishExportChunk, PublishExportResponse]) error {
	return status.Error(codes.Unimplemented, "method PublishExport not implemented")
}
func (UnimplementedDevSpaceServer) PullExport(*PullExportRequest, grpc.ServerStreamingServer[PullExportChunk]) error {
	return status.Error(codes.Unimplemented, "method PullExport not implemented")
}
func (UnimplementedDevSpaceServer) Connect(grpc.BidiStreamingServer[AgentMessage, AgentMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedDevSpaceServer) mustEmbedUnimplementedDevSpaceServer() {}
func (UnimplementedDevSpaceServer) testEmbeddedByValue()                  {}

// UnsafeDevSpaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DevSpaceServer will
// result in compilation errors.
type UnsafeDevSpaceServer interface {
	mustEmbedUnimplementedDevSpaceServer()
}

func RegisterDevSpaceServer(s grpc.ServiceRegistrar, srv DevSpaceServer) {
	// If the following call panics, it indicates UnimplementedDevSpaceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DevSpace_ServiceDesc, srv)
}

func _DevSpace_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevSpaceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevSpace_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevSpaceServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevSpace_DeregisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevSpaceServer).DeregisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevSpace_DeregisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevSpaceServer).DeregisterAgent(ctx, req.(*DeregisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevSpace_ListExports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevSpaceServer).ListExports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevSpace_ListExports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevSpaceServer).ListExports(ctx, req.(*ListExportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevSpace_PublishExport_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DevSpaceServer).PublishExport(&grpc.GenericServerStream[PublishExportChunk, PublishExportResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevSpace_PublishExportServer = grpc.ClientStreamingServer[PublishExportChunk, PublishExportResponse]

func _DevSpace_PullExport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullExportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DevSpaceServer).PullExport(m, &grpc.GenericServerStream[PullExportRequest, PullExportChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevSpace_PullExportServer = grpc.ServerStreamingServer[PullExportChunk]

func _DevSpace_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DevSpaceServer).Connect(&grpc.GenericServerStream[AgentMessage, AgentMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevSpace_ConnectServer = grpc.BidiStreamingServer[AgentMessage, AgentMessage]

// DevSpace_ServiceDesc is the grpc.ServiceDesc for DevSpace service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DevSpace_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mdemg.devspace.v1.DevSpace",
	HandlerType: (*DevSpaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _DevSpace_RegisterAgent_Handler,
		},
		{
			MethodName: "DeregisterAgent",
			Handler:    _DevSpace_DeregisterAgent_Handler,
		},
		{
			MethodName: "ListExports",
			Handler:    _DevSpace_ListExports_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PublishExport",
			Handler:       _DevSpace_PublishExport_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PullExport",
			Handler:       _DevSpace_PullExport_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Connect",
			Handler:       _DevSpace_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/devspace.proto",
}
