// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/devspace.proto

package devspacepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PresenceStatus indicates the current status of an agent.
type PresenceStatus int32

const (
	PresenceStatus_PRESENCE_UNKNOWN PresenceStatus = 0
	PresenceStatus_PRESENCE_ONLINE  PresenceStatus = 1 // Heartbeat within threshold (default: 30s)
	PresenceStatus_PRESENCE_AWAY    PresenceStatus = 2 // Heartbeat within extended threshold (default: 5min)
	PresenceStatus_PRESENCE_OFFLINE PresenceStatus = 3 // No recent heartbeat
)

// Enum value maps for PresenceStatus.
var (
	PresenceStatus_name = map[int32]string{
		0: "PRESENCE_UNKNOWN",
		1: "PRESENCE_ONLINE",
		2: "PRESENCE_AWAY",
		3: "PRESENCE_OFFLINE",
	}
	PresenceStatus_value = map[string]int32{
		"PRESENCE_UNKNOWN": 0,
		"PRESENCE_ONLINE":  1,
		"PRESENCE_AWAY":    2,
		"PRESENCE_OFFLINE": 3,
	}
)

func (x PresenceStatus) Enum() *PresenceStatus {
	p := new(PresenceStatus)
	*p = x
	return p
}

func (x PresenceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PresenceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_devspace_proto_enumTypes[0].Descriptor()
}

func (PresenceStatus) Type() protoreflect.EnumType {
	return &file_api_proto_devspace_proto_enumTypes[0]
}

func (x PresenceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PresenceStatus.Descriptor instead.
func (PresenceStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{0}
}

type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevSpaceId    string                 `protobuf:"bytes,1,opt,name=dev_space_id,json=devSpaceId,proto3" json:"dev_space_id,omitempty"`                                                   // Required: e.g. "my-team"
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                              // Required: unique agent identifier
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional: display name, version, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_api_proto_devspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAgentRequest) GetDevSpaceId() string {
	if x != nil {
		return x.DevSpaceId
	}
	return ""
}

func (x *RegisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_api_proto_devspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAgentResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeregisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevSpaceId    string                 `protobuf:"bytes,1,opt,name=dev_space_id,json=devSpaceId,proto3" json:"dev_space_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterAgentRequest) Reset() {
	*x = DeregisterAgentRequest{}
	mi := &file_api_proto_devspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterAgentRequest) ProtoMessage() {}

func (x *DeregisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterAgentRequest.ProtoReflect.Descriptor instead.
func (*DeregisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterAgentRequest) GetDevSpaceId() string {
	if x != nil {
		return x.DevSpaceId
	}
	return ""
}

func (x *DeregisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type DeregisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterAgentResponse) Reset() {
	*x = DeregisterAgentResponse{}
	mi := &file_api_proto_devspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterAgentResponse) ProtoMessage() {}

func (x *DeregisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterAgentResponse.ProtoReflect.Descriptor instead.
func (*DeregisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterAgentResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListExportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevSpaceId    string                 `protobuf:"bytes,1,opt,name=dev_space_id,json=devSpaceId,proto3" json:"dev_space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExportsRequest) Reset() {
	*x = ListExportsRequest{}
	mi := &file_api_proto_devspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExportsRequest) ProtoMessage() {}

func (x *ListExportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExportsRequest.ProtoReflect.Descriptor instead.
func (*ListExportsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{4}
}

func (x *ListExportsRequest) GetDevSpaceId() string {
	if x != nil {
		return x.DevSpaceId
	}
	return ""
}

type ListExportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exports       []*ExportEntry         `protobuf:"bytes,1,rep,name=exports,proto3" json:"exports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExportsResponse) Reset() {
	*x = ListExportsResponse{}
	mi := &file_api_proto_devspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExportsResponse) ProtoMessage() {}

func (x *ListExportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExportsResponse.ProtoReflect.Descriptor instead.
func (*ListExportsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{5}
}

func (x *ListExportsResponse) GetExports() []*ExportEntry {
	if x != nil {
		return x.Exports
	}
	return nil
}

type ExportEntry struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExportId           string                 `protobuf:"bytes,1,opt,name=export_id,json=exportId,proto3" json:"export_id,omitempty"`          // Hub-assigned ID for pull
	SpaceId            string                 `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`             // MDEMG space_id that was exported
	PublishedAt        string                 `protobuf:"bytes,3,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"` // ISO8601
	PublishedByAgentId string                 `protobuf:"bytes,4,opt,name=published_by_agent_id,json=publishedByAgentId,proto3" json:"published_by_agent_id,omitempty"`
	Label              string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"` // Optional label
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExportEntry) Reset() {
	*x = ExportEntry{}
	mi := &file_api_proto_devspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportEntry) ProtoMessage() {}

func (x *ExportEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportEntry.ProtoReflect.Descriptor instead.
func (*ExportEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{6}
}

func (x *ExportEntry) GetExportId() string {
	if x != nil {
		return x.ExportId
	}
	return ""
}

func (x *ExportEntry) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ExportEntry) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *ExportEntry) GetPublishedByAgentId() string {
	if x != nil {
		return x.PublishedByAgentId
	}
	return ""
}

func (x *ExportEntry) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type PublishExportChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PublishExportChunk_Header
	//	*PublishExportChunk_Data
	Payload       isPublishExportChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishExportChunk) Reset() {
	*x = PublishExportChunk{}
	mi := &file_api_proto_devspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishExportChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishExportChunk) ProtoMessage() {}

func (x *PublishExportChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishExportChunk.ProtoReflect.Descriptor instead.
func (*PublishExportChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{7}
}

func (x *PublishExportChunk) GetPayload() isPublishExportChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishExportChunk) GetHeader() *PublishExportHeader {
	if x != nil {
		if x, ok := x.Payload.(*PublishExportChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *PublishExportChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*PublishExportChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isPublishExportChunk_Payload interface {
	isPublishExportChunk_Payload()
}

type PublishExportChunk_Header struct {
	Header *PublishExportHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"` // First message only
}

type PublishExportChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // Subsequent: raw .mdemg file bytes
}

func (*PublishExportChunk_Header) isPublishExportChunk_Payload() {}

func (*PublishExportChunk_Data) isPublishExportChunk_Payload() {}

type PublishExportHeader struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DevSpaceId         string                 `protobuf:"bytes,1,opt,name=dev_space_id,json=devSpaceId,proto3" json:"dev_space_id,omitempty"`
	SpaceId            string                 `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	PublishedByAgentId string                 `protobuf:"bytes,3,opt,name=published_by_agent_id,json=publishedByAgentId,proto3" json:"published_by_agent_id,omitempty"`
	Label              string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PublishExportHeader) Reset() {
	*x = PublishExportHeader{}
	mi := &file_api_proto_devspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishExportHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishExportHeader) ProtoMessage() {}

func (x *PublishExportHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishExportHeader.ProtoReflect.Descriptor instead.
func (*PublishExportHeader) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{8}
}

func (x *PublishExportHeader) GetDevSpaceId() string {
	if x != nil {
		return x.DevSpaceId
	}
	return ""
}

func (x *PublishExportHeader) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *PublishExportHeader) GetPublishedByAgentId() string {
	if x != nil {
		return x.PublishedByAgentId
	}
	return ""
}

func (x *PublishExportHeader) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type PublishExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExportId      string                 `protobuf:"bytes,1,opt,name=export_id,json=exportId,proto3" json:"export_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishExportResponse) Reset() {
	*x = PublishExportResponse{}
	mi := &file_api_proto_devspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishExportResponse) ProtoMessage() {}

func (x *PublishExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishExportResponse.ProtoReflect.Descriptor instead.
func (*PublishExportResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{9}
}

func (x *PublishExportResponse) GetExportId() string {
	if x != nil {
		return x.ExportId
	}
	return ""
}

func (x *PublishExportResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PublishExportResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PullExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevSpaceId    string                 `protobuf:"bytes,1,opt,name=dev_space_id,json=devSpaceId,proto3" json:"dev_space_id,omitempty"`
	ExportId      string                 `protobuf:"bytes,2,opt,name=export_id,json=exportId,proto3" json:"export_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullExportRequest) Reset() {
	*x = PullExportRequest{}
	mi := &file_api_proto_devspace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullExportRequest) ProtoMessage() {}

func (x *PullExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullExportRequest.ProtoReflect.Descriptor instead.
func (*PullExportRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{10}
}

func (x *PullExportRequest) GetDevSpaceId() string {
	if x != nil {
		return x.DevSpaceId
	}
	return ""
}

func (x *PullExportRequest) GetExportId() string {
	if x != nil {
		return x.ExportId
	}
	return ""
}

type PullExportChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Raw .mdemg file bytes (chunked)
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullExportChunk) Reset() {
	*x = PullExportChunk{}
	mi := &file_api_proto_devspace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullExportChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullExportChunk) ProtoMessage() {}

func (x *PullExportChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullExportChunk.ProtoReflect.Descriptor instead.
func (*PullExportChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{11}
}

func (x *PullExportChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PullExportChunk) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type AgentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevSpaceId    string                 `protobuf:"bytes,1,opt,name=dev_space_id,json=devSpaceId,proto3" json:"dev_space_id,omitempty"`  // Required: target DevSpace
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`             // Sender agent (should be registered)
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`                                // Optional: channel/topic for filtering (e.g. "bugs", "context")
	PayloadType   string                 `protobuf:"bytes,4,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"` // Optional: e.g. "application/json", "text/plain"
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Sequence      int64                  `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"` // Server-assigned order for delivery
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_api_proto_devspace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{12}
}

func (x *AgentMessage) GetDevSpaceId() string {
	if x != nil {
		return x.DevSpaceId
	}
	return ""
}

func (x *AgentMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AgentMessage) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *AgentMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// HeartbeatRequest is sent periodically by agents to indicate they are alive.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevSpaceId    string                 `protobuf:"bytes,1,opt,name=dev_space_id,json=devSpaceId,proto3" json:"dev_space_id,omitempty"`                                               // Required: DevSpace the agent belongs to
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                          // Required: the agent sending the heartbeat
	Status        map[string]string      `protobuf:"bytes,3,rep,name=status,proto3" json:"status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional: status info (e.g. "load": "0.5", "task": "indexing")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_devspace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{13}
}

func (x *HeartbeatRequest) GetDevSpaceId() string {
	if x != nil {
		return x.DevSpaceId
	}
	return ""
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() map[string]string {
	if x != nil {
		return x.Status
	}
	return nil
}

// HeartbeatResponse confirms the heartbeat was received.
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ServerTime    string                 `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // Server timestamp for clock sync (ISO8601)
	QueueSize     int32                  `protobuf:"varint,3,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"`   // Number of queued messages waiting for this agent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_devspace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{14}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

func (x *HeartbeatResponse) GetQueueSize() int32 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

// GetPresenceRequest retrieves the presence status of agents in a DevSpace.
type GetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevSpaceId    string                 `protobuf:"bytes,1,opt,name=dev_space_id,json=devSpaceId,proto3" json:"dev_space_id,omitempty"` // Required: DevSpace to query
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`            // Optional: specific agent (empty = all agents)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceRequest) Reset() {
	*x = GetPresenceRequest{}
	mi := &file_api_proto_devspace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceRequest) ProtoMessage() {}

func (x *GetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{15}
}

func (x *GetPresenceRequest) GetDevSpaceId() string {
	if x != nil {
		return x.DevSpaceId
	}
	return ""
}

func (x *GetPresenceRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// GetPresenceResponse returns the presence status of agents.
type GetPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentPresence       `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceResponse) Reset() {
	*x = GetPresenceResponse{}
	mi := &file_api_proto_devspace_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceResponse) ProtoMessage() {}

func (x *GetPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceResponse.ProtoReflect.Descriptor instead.
func (*GetPresenceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{16}
}

func (x *GetPresenceResponse) GetAgents() []*AgentPresence {
	if x != nil {
		return x.Agents
	}
	return nil
}

// AgentPresence represents the online/offline status of an agent.
type AgentPresence struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AgentId               string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status                PresenceStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=mdemg.devspace.v1.PresenceStatus" json:"status,omitempty"`
	LastHeartbeat         string                 `protobuf:"bytes,3,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`                                                                  // ISO8601 timestamp of last heartbeat
	SecondsSinceHeartbeat int32                  `protobuf:"varint,4,opt,name=seconds_since_heartbeat,json=secondsSinceHeartbeat,proto3" json:"seconds_since_heartbeat,omitempty"`                                       // For convenience
	Metadata              map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                       // Agent metadata from registration
	LastStatus            map[string]string      `protobuf:"bytes,6,rep,name=last_status,json=lastStatus,proto3" json:"last_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Status from last heartbeat
	QueuedMessages        int32                  `protobuf:"varint,7,opt,name=queued_messages,json=queuedMessages,proto3" json:"queued_messages,omitempty"`                                                              // Messages waiting in offline queue
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AgentPresence) Reset() {
	*x = AgentPresence{}
	mi := &file_api_proto_devspace_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPresence) ProtoMessage() {}

func (x *AgentPresence) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPresence.ProtoReflect.Descriptor instead.
func (*AgentPresence) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{17}
}

func (x *AgentPresence) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentPresence) GetStatus() PresenceStatus {
	if x != nil {
		return x.Status
	}
	return PresenceStatus_PRESENCE_UNKNOWN
}

func (x *AgentPresence) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

func (x *AgentPresence) GetSecondsSinceHeartbeat() int32 {
	if x != nil {
		return x.SecondsSinceHeartbeat
	}
	return 0
}

func (x *AgentPresence) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AgentPresence) GetLastStatus() map[string]string {
	if x != nil {
		return x.LastStatus
	}
	return nil
}

func (x *AgentPresence) GetQueuedMessages() int32 {
	if x != nil {
		return x.QueuedMessages
	}
	return 0
}

// SetQueueConfigRequest configures the offline message queue for an agent.
type SetQueueConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevSpaceId    string                 `protobuf:"bytes,1,opt,name=dev_space_id,json=devSpaceId,proto3" json:"dev_space_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	MaxQueueSize  int32                  `protobuf:"varint,3,opt,name=max_queue_size,json=maxQueueSize,proto3" json:"max_queue_size,omitempty"` // Max messages to queue (0 = disable, -1 = unlimited)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetQueueConfigRequest) Reset() {
	*x = SetQueueConfigRequest{}
	mi := &file_api_proto_devspace_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetQueueConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQueueConfigRequest) ProtoMessage() {}

func (x *SetQueueConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQueueConfigRequest.ProtoReflect.Descriptor instead.
func (*SetQueueConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{18}
}

func (x *SetQueueConfigRequest) GetDevSpaceId() string {
	if x != nil {
		return x.DevSpaceId
	}
	return ""
}

func (x *SetQueueConfigRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SetQueueConfigRequest) GetMaxQueueSize() int32 {
	if x != nil {
		return x.MaxQueueSize
	}
	return 0
}

// SetQueueConfigResponse confirms the queue configuration.
type SetQueueConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetQueueConfigResponse) Reset() {
	*x = SetQueueConfigResponse{}
	mi := &file_api_proto_devspace_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetQueueConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQueueConfigResponse) ProtoMessage() {}

func (x *SetQueueConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_devspace_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQueueConfigResponse.ProtoReflect.Descriptor instead.
func (*SetQueueConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_devspace_proto_rawDescGZIP(), []int{19}
}

func (x *SetQueueConfigResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SetQueueConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_devspace_proto protoreflect.FileDescriptor

const file_api_proto_devspace_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/devspace.proto\x12\x11mdemg.devspace.v1\"\xe3\x01\n" +
	"\x14RegisterAgentRequest\x12 \n" +
	"\fdev_space_id\x18\x01 \x01(\tR\n" +
	"devSpaceId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12Q\n" +
	"\bmetadata\x18\x03 \x03(\v25.mdemg.devspace.v1.RegisterAgentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x15RegisterAgentResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"U\n" +
	"\x16DeregisterAgentRequest\x12 \n" +
	"\fdev_space_id\x18\x01 \x01(\tR\n" +
	"devSpaceId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\")\n" +
	"\x17DeregisterAgentResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"6\n" +
	"\x12ListExportsRequest\x12 \n" +
	"\fdev_space_id\x18\x01 \x01(\tR\n" +
	"devSpaceId\"O\n" +
	"\x13ListExportsResponse\x128\n" +
	"\aexports\x18\x01 \x03(\v2\x1e.mdemg.devspace.v1.ExportEntryR\aexports\"\xb1\x01\n" +
	"\vExportEntry\x12\x1b\n" +
	"\texport_id\x18\x01 \x01(\tR\bexportId\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\tR\aspaceId\x12!\n" +
	"\fpublished_at\x18\x03 \x01(\tR\vpublishedAt\x121\n" +
	"\x15published_by_agent_id\x18\x04 \x01(\tR\x12publishedByAgentId\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\"w\n" +
	"\x12PublishExportChunk\x12@\n" +
	"\x06header\x18\x01 \x01(\v2&.mdemg.devspace.v1.PublishExportHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"\x9b\x01\n" +
	"\x13PublishExportHeader\x12 \n" +
	"\fdev_space_id\x18\x01 \x01(\tR\n" +
	"devSpaceId\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\tR\aspaceId\x121\n" +
	"\x15published_by_agent_id\x18\x03 \x01(\tR\x12publishedByAgentId\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\"Z\n" +
	"\x15PublishExportResponse\x12\x1b\n" +
	"\texport_id\x18\x01 \x01(\tR\bexportId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"R\n" +
	"\x11PullExportRequest\x12 \n" +
	"\fdev_space_id\x18\x01 \x01(\tR\n" +
	"devSpaceId\x12\x1b\n" +
	"\texport_id\x18\x02 \x01(\tR\bexportId\"A\n" +
	"\x0fPullExportChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\"\xba\x01\n" +
	"\fAgentMessage\x12 \n" +
	"\fdev_space_id\x18\x01 \x01(\tR\n" +
	"devSpaceId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12!\n" +
	"\fpayload_type\x18\x04 \x01(\tR\vpayloadType\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x03R\bsequence\"\xd3\x01\n" +
	"\x10HeartbeatRequest\x12 \n" +
	"\fdev_space_id\x18\x01 \x01(\tR\n" +
	"devSpaceId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12G\n" +
	"\x06status\x18\x03 \x03(\v2/.mdemg.devspace.v1.HeartbeatRequest.StatusEntryR\x06status\x1a9\n" +
	"\vStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\tR\n" +
	"serverTime\x12\x1d\n" +
	"\n" +
	"queue_size\x18\x03 \x01(\x05R\tqueueSize\"Q\n" +
	"\x12GetPresenceRequest\x12 \n" +
	"\fdev_space_id\x18\x01 \x01(\tR\n" +
	"devSpaceId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"O\n" +
	"\x13GetPresenceResponse\x128\n" +
	"\x06agents\x18\x01 \x03(\v2 .mdemg.devspace.v1.AgentPresenceR\x06agents\"\x88\x04\n" +
	"\rAgentPresence\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.mdemg.devspace.v1.PresenceStatusR\x06status\x12%\n" +
	"\x0elast_heartbeat\x18\x03 \x01(\tR\rlastHeartbeat\x126\n" +
	"\x17seconds_since_heartbeat\x18\x04 \x01(\x05R\x15secondsSinceHeartbeat\x12J\n" +
	"\bmetadata\x18\x05 \x03(\v2..mdemg.devspace.v1.AgentPresence.MetadataEntryR\bmetadata\x12Q\n" +
	"\vlast_status\x18\x06 \x03(\v20.mdemg.devspace.v1.AgentPresence.LastStatusEntryR\n" +
	"lastStatus\x12'\n" +
	"\x0fqueued_messages\x18\a \x01(\x05R\x0equeuedMessages\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fLastStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\x15SetQueueConfigRequest\x12 \n" +
	"\fdev_space_id\x18\x01 \x01(\tR\n" +
	"devSpaceId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12$\n" +
	"\x0emax_queue_size\x18\x03 \x01(\x05R\fmaxQueueSize\">\n" +
	"\x16SetQueueConfigResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*d\n" +
	"\x0ePresenceStatus\x12\x14\n" +
	"\x10PRESENCE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fPRESENCE_ONLINE\x10\x01\x12\x11\n" +
	"\rPRESENCE_AWAY\x10\x02\x12\x14\n" +
	"\x10PRESENCE_OFFLINE\x10\x032\xe2\x06\n" +
	"\bDevSpace\x12b\n" +
	"\rRegisterAgent\x12'.mdemg.devspace.v1.RegisterAgentRequest\x1a(.mdemg.devspace.v1.RegisterAgentResponse\x12h\n" +
	"\x0fDeregisterAgent\x12).mdemg.devspace.v1.DeregisterAgentRequest\x1a*.mdemg.devspace.v1.DeregisterAgentResponse\x12\\\n" +
	"\vListExports\x12%.mdemg.devspace.v1.ListExportsRequest\x1a&.mdemg.devspace.v1.ListExportsResponse\x12b\n" +
	"\rPublishExport\x12%.mdemg.devspace.v1.PublishExportChunk\x1a(.mdemg.devspace.v1.PublishExportResponse(\x01\x12X\n" +
	"\n" +
	"PullExport\x12$.mdemg.devspace.v1.PullExportRequest\x1a\".mdemg.devspace.v1.PullExportChunk0\x01\x12O\n" +
	"\aConnect\x12\x1f.mdemg.devspace.v1.AgentMessage\x1a\x1f.mdemg.devspace.v1.AgentMessage(\x010\x01\x12V\n" +
	"\tHeartbeat\x12#.mdemg.devspace.v1.HeartbeatRequest\x1a$.mdemg.devspace.v1.HeartbeatResponse\x12\\\n" +
	"\vGetPresence\x12%.mdemg.devspace.v1.GetPresenceRequest\x1a&.mdemg.devspace.v1.GetPresenceResponse\x12e\n" +
	"\x0eSetQueueConfig\x12(.mdemg.devspace.v1.SetQueueConfigRequest\x1a).mdemg.devspace.v1.SetQueueConfigResponseB\x16Z\x14mdemg/api/devspacepbb\x06proto3"

var (
	file_api_proto_devspace_proto_rawDescOnce sync.Once
	file_api_proto_devspace_proto_rawDescData []byte
)

func file_api_proto_devspace_proto_rawDescGZIP() []byte {
	file_api_proto_devspace_proto_rawDescOnce.Do(func() {
		file_api_proto_devspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_devspace_proto_rawDesc), len(file_api_proto_devspace_proto_rawDesc)))
	})
	return file_api_proto_devspace_proto_rawDescData
}

var file_api_proto_devspace_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_devspace_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_proto_devspace_proto_goTypes = []any{
	(PresenceStatus)(0),             // 0: mdemg.devspace.v1.PresenceStatus
	(*RegisterAgentRequest)(nil),    // 1: mdemg.devspace.v1.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),   // 2: mdemg.devspace.v1.RegisterAgentResponse
	(*DeregisterAgentRequest)(nil),  // 3: mdemg.devspace.v1.DeregisterAgentRequest
	(*DeregisterAgentResponse)(nil), // 4: mdemg.devspace.v1.DeregisterAgentResponse
	(*ListExportsRequest)(nil),      // 5: mdemg.devspace.v1.ListExportsRequest
	(*ListExportsResponse)(nil),     // 6: mdemg.devspace.v1.ListExportsResponse
	(*ExportEntry)(nil),             // 7: mdemg.devspace.v1.ExportEntry
	(*PublishExportChunk)(nil),      // 8: mdemg.devspace.v1.PublishExportChunk
	(*PublishExportHeader)(nil),     // 9: mdemg.devspace.v1.PublishExportHeader
	(*PublishExportResponse)(nil),   // 10: mdemg.devspace.v1.PublishExportResponse
	(*PullExportRequest)(nil),       // 11: mdemg.devspace.v1.PullExportRequest
	(*PullExportChunk)(nil),         // 12: mdemg.devspace.v1.PullExportChunk
	(*AgentMessage)(nil),            // 13: mdemg.devspace.v1.AgentMessage
	(*HeartbeatRequest)(nil),        // 14: mdemg.devspace.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 15: mdemg.devspace.v1.HeartbeatResponse
	(*GetPresenceRequest)(nil),      // 16: mdemg.devspace.v1.GetPresenceRequest
	(*GetPresenceResponse)(nil),     // 17: mdemg.devspace.v1.GetPresenceResponse
	(*AgentPresence)(nil),           // 18: mdemg.devspace.v1.AgentPresence
	(*SetQueueConfigRequest)(nil),   // 19: mdemg.devspace.v1.SetQueueConfigRequest
	(*SetQueueConfigResponse)(nil),  // 20: mdemg.devspace.v1.SetQueueConfigResponse
	nil,                             // 21: mdemg.devspace.v1.RegisterAgentRequest.MetadataEntry
	nil,                             // 22: mdemg.devspace.v1.HeartbeatRequest.StatusEntry
	nil,                             // 23: mdemg.devspace.v1.AgentPresence.MetadataEntry
	nil,                             // 24: mdemg.devspace.v1.AgentPresence.LastStatusEntry
}
var file_api_proto_devspace_proto_depIdxs = []int32{
	21, // 0: mdemg.devspace.v1.RegisterAgentRequest.metadata:type_name -> mdemg.devspace.v1.RegisterAgentRequest.MetadataEntry
	7,  // 1: mdemg.devspace.v1.ListExportsResponse.exports:type_name -> mdemg.devspace.v1.ExportEntry
	9,  // 2: mdemg.devspace.v1.PublishExportChunk.header:type_name -> mdemg.devspace.v1.PublishExportHeader
	22, // 3: mdemg.devspace.v1.HeartbeatRequest.status:type_name -> mdemg.devspace.v1.HeartbeatRequest.StatusEntry
	18, // 4: mdemg.devspace.v1.GetPresenceResponse.agents:type_name -> mdemg.devspace.v1.AgentPresence
	0,  // 5: mdemg.devspace.v1.AgentPresence.status:type_name -> mdemg.devspace.v1.PresenceStatus
	23, // 6: mdemg.devspace.v1.AgentPresence.metadata:type_name -> mdemg.devspace.v1.AgentPresence.MetadataEntry
	24, // 7: mdemg.devspace.v1.AgentPresence.last_status:type_name -> mdemg.devspace.v1.AgentPresence.LastStatusEntry
	1,  // 8: mdemg.devspace.v1.DevSpace.RegisterAgent:input_type -> mdemg.devspace.v1.RegisterAgentRequest
	3,  // 9: mdemg.devspace.v1.DevSpace.DeregisterAgent:input_type -> mdemg.devspace.v1.DeregisterAgentRequest
	5,  // 10: mdemg.devspace.v1.DevSpace.ListExports:input_type -> mdemg.devspace.v1.ListExportsRequest
	8,  // 11: mdemg.devspace.v1.DevSpace.PublishExport:input_type -> mdemg.devspace.v1.PublishExportChunk
	11, // 12: mdemg.devspace.v1.DevSpace.PullExport:input_type -> mdemg.devspace.v1.PullExportRequest
	13, // 13: mdemg.devspace.v1.DevSpace.Connect:input_type -> mdemg.devspace.v1.AgentMessage
	14, // 14: mdemg.devspace.v1.DevSpace.Heartbeat:input_type -> mdemg.devspace.v1.HeartbeatRequest
	16, // 15: mdemg.devspace.v1.DevSpace.GetPresence:input_type -> mdemg.devspace.v1.GetPresenceRequest
	19, // 16: mdemg.devspace.v1.DevSpace.SetQueueConfig:input_type -> mdemg.devspace.v1.SetQueueConfigRequest
	2,  // 17: mdemg.devspace.v1.DevSpace.RegisterAgent:output_type -> mdemg.devspace.v1.RegisterAgentResponse
	4,  // 18: mdemg.devspace.v1.DevSpace.DeregisterAgent:output_type -> mdemg.devspace.v1.DeregisterAgentResponse
	6,  // 19: mdemg.devspace.v1.DevSpace.ListExports:output_type -> mdemg.devspace.v1.ListExportsResponse
	10, // 20: mdemg.devspace.v1.DevSpace.PublishExport:output_type -> mdemg.devspace.v1.PublishExportResponse
	12, // 21: mdemg.devspace.v1.DevSpace.PullExport:output_type -> mdemg.devspace.v1.PullExportChunk
	13, // 22: mdemg.devspace.v1.DevSpace.Connect:output_type -> mdemg.devspace.v1.AgentMessage
	15, // 23: mdemg.devspace.v1.DevSpace.Heartbeat:output_type -> mdemg.devspace.v1.HeartbeatResponse
	17, // 24: mdemg.devspace.v1.DevSpace.GetPresence:output_type -> mdemg.devspace.v1.GetPresenceResponse
	20, // 25: mdemg.devspace.v1.DevSpace.SetQueueConfig:output_type -> mdemg.devspace.v1.SetQueueConfigResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_devspace_proto_init() }
func file_api_proto_devspace_proto_init() {
	if File_api_proto_devspace_proto != nil {
		return
	}
	file_api_proto_devspace_proto_msgTypes[7].OneofWrappers = []any{
		(*PublishExportChunk_Header)(nil),
		(*PublishExportChunk_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_devspace_proto_rawDesc), len(file_api_proto_devspace_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_devspace_proto_goTypes,
		DependencyIndexes: file_api_proto_devspace_proto_depIdxs,
		EnumInfos:         file_api_proto_devspace_proto_enumTypes,
		MessageInfos:      file_api_proto_devspace_proto_msgTypes,
	}.Build()
	File_api_proto_devspace_proto = out.File
	file_api_proto_devspace_proto_goTypes = nil
	file_api_proto_devspace_proto_depIdxs = nil
}
